window.MEDINDEX_ATC_GROUPS = {
  A: 'Tretja dhe metabolizmi',
  B: 'Gjaku dhe organet gjakformuese',
  C: 'Sistemi kardiovaskular',
  D: 'Barna dermatologjike',
  G: 'Sistemi gjenitourinar dhe hormonet seksuale',
  H: 'Hormonet sistemike',
  J: 'Antiinfektivë për përdorim sistemik',
  L: 'Antineoplastikë dhe imunomodulues',
  M: 'Sistemi muskuloskeletal',
  N: 'Sistemi nervor',
  P: 'Barna antiparazitare',
  R: 'Sistemi respirator',
  S: 'Organet shqisore',
  V: 'Produkte të ndryshme'
};

window.MEDINDEX_ATC_SUBGROUPS = {
  A01: 'Barna për gojën dhe stomatologji',
  A02: 'Barna kundër aciditetit dhe ulçerës',
  A03: 'Barna për çrregullimet funksionale gastrointestinale',
  A04: 'Barna kundër të përzierave dhe vjelljes',
  A05: 'Barna për mëlçinë dhe rrugët biliare',
  A06: 'Laksativë – kundër kapsllëkut',
  A07: 'Kundër diarresë, infeksioneve dhe inflamacionit intestinal',
  A08: 'Barna kundër obezitetit',
  A09: 'Enzima dhe barna ndihmëse për tretje',
  A10: 'Barna për diabetin',
  A11: 'Vitamina',
  A12: 'Minerale dhe elektrolite',
  A16: 'Barna të tjera metabolike',

  B01: 'Barna antitrombotike – kundër formimit të trombeve',
  B02: 'Barna kundër gjakderdhjes',
  B03: 'Barna kundër anemisë',
  B05: 'Zëvendësues të gjakut dhe tretësira për infuzion',

  C01: 'Barna për sëmundjet e zemrës',
  C02: 'Barna antihipertensive',
  C03: 'Diuretikë',
  C04: 'Vazodilatatorë periferikë',
  C05: 'Barna vazoprotektive dhe për hemorroide/vena',
  C07: 'Beta-bllokues',
  C08: 'Bllokues të kanaleve të kalciumit',
  C09: 'Barna që veprojnë në sistemin reninë–angiotensinë',
  C10: 'Barna për uljen e lipideve dhe kolesterolit',

  D01: 'Barna antifungale për përdorim dermatologjik',
  D03: 'Barna për trajtimin e plagëve dhe ulçerave të lëkurës',
  D04: 'Barna kundër kruajtjes dhe reaksioneve alergjike të lëkurës',
  D05: 'Barna kundër psoriazës',
  D06: 'Antibiotikë dhe antimikrobikë për përdorim dermatologjik',
  D07: 'Kortikosteroide për përdorim dermatologjik',
  D08: 'Antiseptikë dhe dezinfektues',
  D10: 'Barna kundër akneve',
  D11: 'Barna të tjera dermatologjike',

  G01: 'Barna antiinfektive dhe antiseptike gjinekologjike',
  G02: 'Barna të tjera gjinekologjike',
  G03: 'Hormone seksuale dhe modulues të sistemit gjenital',
  G04: 'Barna urologjike',

  H01: 'Hormonet e hipofizës dhe hipotalamusit dhe analogët e tyre',
  H02: 'Kortikosteroide për përdorim sistemik',
  H03: 'Barna për trajtimin e gjëndrës tiroide',
  H05: 'Barna që rregullojnë homeostazën e kalciumit',

  J01: 'Antibiotikë për përdorim sistemik',
  J02: 'Barna antifungale për përdorim sistemik',
  J05: 'Barna antivirale për përdorim sistemik',
  J06: 'Serume imune dhe imunoglobulina',
  J07: 'Vaksina',

  L01: 'Barna antineoplastike – kundër kancerit',
  L02: 'Terapi endokrine për trajtimin e tumoreve hormonale',
  L03: 'Imunostimulues',
  L04: 'Imunosupresivë',

  M01: 'Barna antiinflamatore dhe antireumatike',
  M02: 'Barna lokale për dhimbjet e muskujve dhe nyjave',
  M03: 'Relaksues të muskujve',
  M04: 'Barna kundër përdhes – hiperuricemisë',
  M05: 'Barna për trajtimin e sëmundjeve të kockave',
  M09: 'Barna të tjera për sistemin muskuloskeletal',

  N01: 'Anestetikë',
  N02: 'Analgjetikë – barna kundër dhimbjes',
  N03: 'Antiepileptikë',
  N04: 'Barna kundër Parkinsonit',
  N05: 'Psikoleptikë – antipsikotikë, anksiolitikë dhe sedativë',
  N06: 'Psikoanaleptikë – antidepresivë dhe barna për demencë/ADHD',
  N07: 'Barna të tjera për sistemin nervor',

  P01: 'Barna kundër protozoarëve dhe malaries',
  P02: 'Barna kundër krimbave – antihelmintikë',
  P03: 'Barna kundër parazitëve të jashtëm, zgjebes dhe morrave',

  R01: 'Barna për hundën – dekongjestivë dhe preparate nazale',
  R02: 'Barna për fytin',
  R03: 'Barna për sëmundjet obstruktive të rrugëve të frymëmarrjes',
  R05: 'Barna kundër kollës dhe ftohjes',
  R06: 'Antihistaminikë për përdorim sistemik',
  R07: 'Barna të tjera për sistemin respirator',

  S01: 'Barna oftalmologjike – preparate për sytë',
  S02: 'Barna otologjike – preparate për veshët',
  S03: 'Preparate për sy dhe vesh',

  V03: 'Produkte të tjera terapeutike, antidote dhe preparate të veçanta',
  V06: 'Preparate ushqyese të përgjithshme',
  V07: 'Produkte të tjera joterapeutike dhe tretës për barna',
  V08: 'Mjete kontrasti për ekzaminime radiologjike dhe MRI'
};

// Nënndarjet e ATC-së: niveli 4 (nëngrupi farmakologjik) dhe niveli 5 (nëngrupi
// kimik). Grupi dhe kategoria kishin emra; këto nuk kishin, prandaj shfletimi i
// pemës arrinte te rreshta pa emër. Emrat janë terminologjia zyrtare e ATC-së e
// dhënë në shqip, jo përshkrime të krijuara për kodin.
window.MEDINDEX_ATC_SUBDIVISIONS = {
  A01A: 'Preparate stomatologjike',
  A02A: 'Antacidë',
  A02B: 'Barna kundër ulçerës peptike dhe refluksit gastroezofageal',
  A03A: 'Barna kundër spazmave funksionale të zorrëve',
  A03B: 'Belladona dhe derivate',
  A03D: 'Antispazmatikë në kombinim me analgjezikë',
  A03F: 'Prokinetikë – nxitës të lëvizshmërisë së zorrëve',
  A04A: 'Barna kundër të përzierave dhe vjelljes',
  A05A: 'Barna për rrugët biliare',
  A05B: 'Barna për mëlçinë – lipotropikë',
  A06A: 'Laksativë',
  A07A: 'Antiinfektivë intestinalë',
  A07B: 'Adsorbentë intestinalë',
  A07C: 'Elektrolite me karbohidrate – tretësira rehidruese',
  A07D: 'Barna që ngadalësojnë lëvizshmërinë e zorrëve',
  A07E: 'Antiinflamatorë intestinalë',
  A07F: 'Mikroorganizma kundër diarresë – probiotikë',
  A07X: 'Barna të tjera kundër diarresë',
  A08A: 'Barna kundër obezitetit',
  A09A: 'Enzima zëvendësuese të tretjes',
  A10A: 'Insulina dhe analoge',
  A10B: 'Barna që ulin glukozën në gjak, përveç insulinave',
  A11A: 'Multivitamina në kombinim me minerale të tjera',
  A11B: 'Multivitamina të thjeshta',
  A11C: 'Vitamina A dhe D, përfshirë kombinimet',
  A11D: 'Vitamina B1 dhe kombinimet e saj',
  A11E: 'Kompleksi i vitaminës B, përfshirë kombinimet',
  A11G: 'Vitamina C dhe kombinimet e saj',
  A11H: 'Preparate të tjera vitaminash të thjeshta',
  A12A: 'Preparate kalciumi',
  A12B: 'Preparate kaliumi',
  A12C: 'Minerale të tjera',
  A16A: 'Produkte të tjera për traktin tretës dhe metabolizmin',

  B01A: 'Barna antitrombotike',
  B02A: 'Antifibrinolitikë',
  B02B: 'Vitamina K dhe hemostatikë të tjerë',
  B03A: 'Preparate hekuri',
  B03B: 'Vitamina B12 dhe acidi folik',
  B03X: 'Preparate të tjera kundër anemisë',
  B05A: 'Gjaku dhe produktet e tij',
  B05B: 'Tretësira për infuzion intravenoz',
  B05C: 'Tretësira shpëlarëse',
  B05D: 'Tretësira për dializë peritoneale',
  B05X: 'Aditivë për tretësira intravenoze',

  C01A: 'Glikozide kardiake',
  C01B: 'Antiaritmikë, klasa I dhe III',
  C01C: 'Stimulues kardiakë, përveç glikozideve kardiake',
  C01D: 'Vazodilatatorë për sëmundjet e zemrës',
  C01E: 'Preparate të tjera kardiake',
  C02A: 'Antiadrenergjikë me veprim qendror',
  C02C: 'Antiadrenergjikë me veprim periferik',
  C03A: 'Diuretikë tiazidikë',
  C03B: 'Diuretikë të tjerë me veprim mesatar',
  C03C: 'Diuretikë të lakut – me veprim të fuqishëm',
  C03D: 'Diuretikë që kursejnë kaliumin',
  C03E: 'Diuretikë në kombinim me kursyes të kaliumit',
  C04A: 'Vazodilatatorë periferikë',
  C05A: 'Barna lokale kundër hemorroideve dhe çarjeve anale',
  C05B: 'Barna kundër varikozitetit',
  C05C: 'Barna që stabilizojnë kapilarët',
  C07A: 'Beta-bllokues',
  C07C: 'Beta-bllokues në kombinim me diuretikë të tjerë',
  C08C: 'Bllokues selektivë të kanaleve të kalciumit me veprim vaskular',
  C08D: 'Bllokues selektivë të kanaleve të kalciumit me veprim kardiak',
  C09A: 'Frenues të enzimës konvertuese të angiotenzinës – ACE',
  C09B: 'Frenues të ACE-së në kombinim',
  C09C: 'Antagonistë të receptorit të angiotenzinës II – sartanë',
  C09D: 'Antagonistë të receptorit të angiotenzinës II në kombinim',
  C10A: 'Barna që ulin kolesterolin dhe triglicerinat',
  C10B: 'Barna që ulin lipidet, në kombinim',

  D01A: 'Antifungikë për përdorim lokal',
  D01B: 'Antifungikë sistemikë për infeksionet e lëkurës',
  D03A: 'Barna që nxisin shërimin e plagëve',
  D04A: 'Barna kundër kruajtjes, përfshirë antihistaminikët lokalë',
  D05A: 'Preparate lokale kundër psoriazës',
  D05B: 'Preparate sistemike kundër psoriazës',
  D06A: 'Antibiotikë për përdorim lokal',
  D06B: 'Kemioterapeutikë për përdorim lokal',
  D07A: 'Kortikosteroide dermatologjike të thjeshta',
  D07B: 'Kortikosteroide në kombinim me antiseptikë',
  D07C: 'Kortikosteroide në kombinim me antibiotikë',
  D07X: 'Kortikosteroide në kombinime të tjera',
  D08A: 'Antiseptikë dhe dezinfektues',
  D10A: 'Preparate lokale kundër aknes',
  D10B: 'Preparate sistemike kundër aknes',
  D11A: 'Preparate të tjera dermatologjike',

  G01A: 'Antiinfektivë dhe antiseptikë gjinekologjikë',
  G01B: 'Antiinfektivë gjinekologjikë në kombinim me kortikosteroide',
  G02A: 'Uterotonikë – nxitës të kontraktimit të mitrës',
  G02C: 'Barna të tjera gjinekologjike',
  G03A: 'Kontraceptivë hormonalë për përdorim sistemik',
  G03B: 'Androgjene',
  G03C: 'Estrogjene',
  G03D: 'Progestogjene',
  G03F: 'Progestogjene dhe estrogjene në kombinim',
  G03G: 'Gonadotropina dhe stimulues të ovulacionit',
  G03H: 'Antiandrogjene',
  G04B: 'Barna të tjera urologjike, përfshirë antispazmatikët',
  G04C: 'Barna për hipertrofinë beninje të prostatës',

  H01A: 'Hormonet e lobit të përparmë të hipofizës dhe analoge',
  H01B: 'Hormonet e lobit të pasmë të hipofizës',
  H01C: 'Hormonet hipotalamike',
  H02A: 'Kortikosteroide sistemike të thjeshta',
  H03A: 'Preparate tiroide',
  H03B: 'Barna antitiroide',
  H05B: 'Barna kundër paratiroides – që ulin kalciumin',

  J01A: 'Tetraciklina',
  J01C: 'Antibakterialë beta-laktamikë – penicilina',
  J01D: 'Antibakterialë të tjerë beta-laktamikë – cefalosporina dhe karbapeneme',
  J01E: 'Sulfonamide dhe trimetoprim',
  J01F: 'Makrolide, linkozamide dhe streptogramina',
  J01G: 'Antibakterialë aminoglikozide',
  J01M: 'Antibakterialë kinolone',
  J01R: 'Kombinime antibakterialësh',
  J01X: 'Antibakterialë të tjerë',
  J02A: 'Antifungikë për përdorim sistemik',
  J05A: 'Antiviralë me veprim të drejtpërdrejtë',
  J06B: 'Imunoglobulina',
  J07A: 'Vaksina bakteriale',
  J07B: 'Vaksina virale',
  J07C: 'Vaksina bakteriale dhe virale të kombinuara',

  L01A: 'Agjentë alkilues',
  L01B: 'Antimetabolitë',
  L01C: 'Alkaloide bimore dhe produkte të tjera natyrale',
  L01D: 'Antibiotikë citotoksikë dhe substanca të ngjashme',
  L01E: 'Frenues të proteinkinazave',
  L01F: 'Antitrupa monoklonalë dhe konjugatë antitrup–bar',
  L01X: 'Agjentë të tjerë antineoplastikë',
  L02A: 'Hormone dhe agjentë të ngjashëm në terapinë e kancerit',
  L02B: 'Antagonistë hormonalë dhe agjentë të ngjashëm',
  L03A: 'Imunostimulues',
  L04A: 'Imunosupresivë',

  M01A: 'Antiinflamatorë dhe antireumatikë josteroidë',
  M01B: 'Antiinflamatorë josteroidë në kombinim',
  M02A: 'Preparate lokale për dhimbje të kyçeve dhe muskujve',
  M03A: 'Relaksues muskulorë me veprim periferik',
  M03B: 'Relaksues muskulorë me veprim qendror',
  M04A: 'Barna kundër përdhesit',
  M05B: 'Barna që veprojnë në strukturën dhe mineralizimin e kockës',
  M09A: 'Barna të tjera për çrregullimet muskuloskeletale',

  N01A: 'Anestetikë të përgjithshëm',
  N01B: 'Anestetikë lokalë',
  N02A: 'Opioide',
  N02B: 'Analgjezikë dhe antipiretikë të tjerë',
  N02C: 'Preparate kundër migrenës',
  N03A: 'Barna antiepileptike',
  N04A: 'Barna antikolinergjike kundër parkinsonizmit',
  N04B: 'Barna dopaminergjike kundër Parkinsonit',
  N05A: 'Antipsikotikë',
  N05B: 'Anksiolitikë',
  N05C: 'Hipnotikë dhe sedativë',
  N06A: 'Antidepresivë',
  N06B: 'Psikostimulues dhe nootropikë',
  N06C: 'Psikoleptikë dhe psikoanaleptikë në kombinim',
  N06D: 'Barna kundër demencës',
  N07A: 'Parasimpatikomimetikë',
  N07B: 'Barna që përdoren në varësitë',
  N07C: 'Barna kundër marrjes së mendsh – vertigos',

  P01A: 'Barna kundër amebiazës dhe infeksioneve të tjera protozoare',
  P01B: 'Barna kundër malaries',
  P02C: 'Barna kundër nematodave – krimbave të rrumbullakët',
  P03A: 'Barna kundër ektoparazitëve, përfshirë zgjebën',

  R01A: 'Dekongjestivë dhe preparate të tjera nazale për përdorim lokal',
  R01B: 'Dekongjestivë nazalë për përdorim sistemik',
  R02A: 'Preparate për fytin',
  R03A: 'Adrenergjikë të inhaluar',
  R03B: 'Barna të tjera të inhaluara për sëmundjet obstruktive të rrugëve të frymëmarrjes',
  R03C: 'Adrenergjikë për përdorim sistemik',
  R03D: 'Barna të tjera sistemike për sëmundjet obstruktive të rrugëve të frymëmarrjes',
  R05C: 'Ekspektorantë, pa qetësues të kollës',
  R05D: 'Qetësues të kollës, pa ekspektorantë',
  R05X: 'Preparate të tjera kundër ftohjes',
  R06A: 'Antihistaminikë për përdorim sistemik',
  R07A: 'Produkte të tjera për sistemin respirator',

  S01A: 'Antiinfektivë okularë',
  S01B: 'Antiinflamatorë okularë',
  S01C: 'Antiinflamatorë dhe antiinfektivë okularë në kombinim',
  S01E: 'Barna kundër glaukomës dhe miotikë',
  S01F: 'Midriatikë dhe cikloplegjikë',
  S01G: 'Dekongjestivë dhe antialergjikë okularë',
  S01L: 'Barna për çrregullimet vaskulare të syrit',
  S01H: 'Anestetikë lokalë okularë',
  S01X: 'Preparate të tjera oftalmologjike',
  S02A: 'Antiinfektivë për veshin',
  S02C: 'Kortikosteroide dhe antiinfektivë për veshin në kombinim',
  S03A: 'Antiinfektivë për sy dhe vesh',
  S03B: 'Kortikosteroide për sy dhe vesh',
  S03C: 'Kortikosteroide dhe antiinfektivë për sy dhe vesh në kombinim',

  V03A: 'Produkte të tjera terapeutike',
  V06D: 'Ushqime të tjera dietike',
  V07A: 'Produkte të tjera jo-terapeutike',
  V08A: 'Mjete kontrasti me jod për rreze X',
  V08C: 'Mjete kontrasti për rezonancë magnetike',

  // Niveli 5 — nëngrupi kimik. Shfaqet vetëm kur nëngrupi farmakologjik është
  // shumë i madh për t'u hapur drejtpërdrejt në barna.
  B01AA: 'Antagonistë të vitaminës K',
  B01AB: 'Grupi i heparinës',
  B01AC: 'Frenues të agregimit të trombociteve, përveç heparinës',
  B01AD: 'Enzima trombolitike',
  B01AF: 'Frenues të drejtpërdrejtë të faktorit Xa',
  B01AX: 'Barna të tjera antitrombotike',

  C09DA: 'Sartanë në kombinim me diuretikë',
  C09DB: 'Sartanë në kombinim me bllokues të kanaleve të kalciumit',
  C09DX: 'Sartanë në kombinime të tjera',

  J01CA: 'Penicilina me spektër të gjerë',
  J01CE: 'Penicilina të ndjeshme ndaj beta-laktamazës',
  J01CF: 'Penicilina rezistente ndaj beta-laktamazës',
  J01CR: 'Penicilina në kombinim me frenues të beta-laktamazës',
  J01DB: 'Cefalosporina të gjeneratës së parë',
  J01DC: 'Cefalosporina të gjeneratës së dytë',
  J01DD: 'Cefalosporina të gjeneratës së tretë',
  J01DE: 'Cefalosporina të gjeneratës së katërt',
  J01DH: 'Karbapeneme',
  J01DI: 'Cefalosporina të tjera dhe peneme',

  M01AA: 'Butilpirazolidina',
  M01AB: 'Derivate të acidit acetik dhe substanca të ngjashme',
  M01AC: 'Oksikamë',
  M01AE: 'Derivate të acidit propionik',
  M01AG: 'Fenamatë',
  M01AH: 'Frenues selektivë të COX-2 – koksibë',
  M01AX: 'Antiinflamatorë dhe antireumatikë të tjerë josteroidë',

  N02AA: 'Alkaloide natyrale të opiumit',
  N02AB: 'Derivate të fenilpiperidinës',
  N02AE: 'Derivate të oripavinës',
  N02AJ: 'Opioide në kombinim me analgjezikë josteroidë',
  N02AX: 'Opioide të tjera',
  N02BA: 'Acidi salicilik dhe derivate',
  N02BB: 'Pirazolone',
  N02BE: 'Anilide',
  N02BF: 'Gabapentinoide'
};
