window.MEDINDEX_ATC_GROUPS = {
  A: 'Tretja dhe metabolizmi',
  B: 'Gjaku dhe organet gjakformuese',
  C: 'Sistemi kardiovaskular',
  D: 'Barna dermatologjike',
  G: 'Sistemi gjenitourinar dhe hormonet seksuale',
  H: 'Hormonet sistemike',
  J: 'Antiinfektivë për përdorim sistemik',
  L: 'Antineoplastikë dhe imunomodulues',
  M: 'Sistemi muskuloskeletal',
  N: 'Sistemi nervor',
  P: 'Barna antiparazitare',
  R: 'Sistemi respirator',
  S: 'Organet shqisore',
  V: 'Produkte të ndryshme'
};

window.MEDINDEX_ATC_SUBGROUPS = {
  A01: 'Barna për gojën dhe stomatologji',
  A02: 'Barna kundër aciditetit dhe ulçerës',
  A03: 'Barna për çrregullimet funksionale gastrointestinale',
  A04: 'Barna kundër të përzierave dhe vjelljes',
  A05: 'Barna për mëlçinë dhe rrugët biliare',
  A06: 'Laksativë – kundër kapsllëkut',
  A07: 'Kundër diarresë, infeksioneve dhe inflamacionit intestinal',
  A08: 'Barna kundër obezitetit',
  A09: 'Enzima dhe barna ndihmëse për tretje',
  A10: 'Barna për diabetin',
  A11: 'Vitamina',
  A12: 'Minerale dhe elektrolite',
  A16: 'Barna të tjera metabolike',

  B01: 'Barna antitrombotike – kundër formimit të trombeve',
  B02: 'Barna kundër gjakderdhjes',
  B03: 'Barna kundër anemisë',
  B05: 'Zëvendësues të gjakut dhe tretësira për infuzion',

  C01: 'Barna për sëmundjet e zemrës',
  C02: 'Barna antihipertensive',
  C03: 'Diuretikë',
  C04: 'Vazodilatatorë periferikë',
  C05: 'Barna vazoprotektive dhe për hemorroide/vena',
  C07: 'Beta-bllokues',
  C08: 'Bllokues të kanaleve të kalciumit',
  C09: 'Barna që veprojnë në sistemin reninë–angiotensinë',
  C10: 'Barna për uljen e lipideve dhe kolesterolit',

  D01: 'Barna antifungale për përdorim dermatologjik',
  D03: 'Barna për trajtimin e plagëve dhe ulçerave të lëkurës',
  D04: 'Barna kundër kruajtjes dhe reaksioneve alergjike të lëkurës',
  D05: 'Barna kundër psoriazës',
  D06: 'Antibiotikë dhe antimikrobikë për përdorim dermatologjik',
  D07: 'Kortikosteroide për përdorim dermatologjik',
  D08: 'Antiseptikë dhe dezinfektues',
  D10: 'Barna kundër akneve',
  D11: 'Barna të tjera dermatologjike',

  G01: 'Barna antiinfektive dhe antiseptike gjinekologjike',
  G02: 'Barna të tjera gjinekologjike',
  G03: 'Hormone seksuale dhe modulues të sistemit gjenital',
  G04: 'Barna urologjike',

  H01: 'Hormonet e hipofizës dhe hipotalamusit dhe analogët e tyre',
  H02: 'Kortikosteroide për përdorim sistemik',
  H03: 'Barna për trajtimin e gjëndrës tiroide',
  H05: 'Barna që rregullojnë homeostazën e kalciumit',

  J01: 'Antibiotikë për përdorim sistemik',
  J02: 'Barna antifungale për përdorim sistemik',
  J05: 'Barna antivirale për përdorim sistemik',
  J06: 'Serume imune dhe imunoglobulina',
  J07: 'Vaksina',

  L01: 'Barna antineoplastike – kundër kancerit',
  L02: 'Terapi endokrine për trajtimin e tumoreve hormonale',
  L03: 'Imunostimulues',
  L04: 'Imunosupresivë',

  M01: 'Barna antiinflamatore dhe antireumatike',
  M02: 'Barna lokale për dhimbjet e muskujve dhe nyjave',
  M03: 'Relaksues të muskujve',
  M04: 'Barna kundër përdhes – hiperuricemisë',
  M05: 'Barna për trajtimin e sëmundjeve të kockave',
  M09: 'Barna të tjera për sistemin muskuloskeletal',

  N01: 'Anestetikë',
  N02: 'Analgjetikë – barna kundër dhimbjes',
  N03: 'Antiepileptikë',
  N04: 'Barna kundër Parkinsonit',
  N05: 'Psikoleptikë – antipsikotikë, anksiolitikë dhe sedativë',
  N06: 'Psikoanaleptikë – antidepresivë dhe barna për demencë/ADHD',
  N07: 'Barna të tjera për sistemin nervor',

  P01: 'Barna kundër protozoarëve dhe malaries',
  P02: 'Barna kundër krimbave – antihelmintikë',
  P03: 'Barna kundër parazitëve të jashtëm, zgjebes dhe morrave',

  R01: 'Barna për hundën – dekongjestivë dhe preparate nazale',
  R02: 'Barna për fytin',
  R03: 'Barna për sëmundjet obstruktive të rrugëve të frymëmarrjes',
  R05: 'Barna kundër kollës dhe ftohjes',
  R06: 'Antihistaminikë për përdorim sistemik',
  R07: 'Barna të tjera për sistemin respirator',

  S01: 'Barna oftalmologjike – preparate për sytë',
  S02: 'Barna otologjike – preparate për veshët',
  S03: 'Preparate për sy dhe vesh',

  V03: 'Produkte të tjera terapeutike, antidote dhe preparate të veçanta',
  V06: 'Preparate ushqyese të përgjithshme',
  V07: 'Produkte të tjera joterapeutike dhe tretës për barna',
  V08: 'Mjete kontrasti për ekzaminime radiologjike dhe MRI'
};
