(() => {
  'use strict';
  const FORM_SOURCE = 'Formular laboratorik i Ministrisë së Shëndetësisë së Kosovës, © 2008, i dërguar nga përdoruesja.';
  const ANALYZER_SOURCE = 'Printim i analizatorit hematologjik, 22.07.2026, i dërguar nga përdoruesja.';
  const make = row => {
    const [id, system, name, abbr, specimen, reference, unit, alternateReference, referenceNote, source] = row;
    return { id, system, name, abbr, specimen, reference, unit, alternateReference, referenceNote, kosovoCore: true,
      why: 'Analizë e listuar në formularët laboratorikë të dërguar nga përdoruesja.',
      high: 'Formulari i fotografuar nuk jep interpretim klinik të vlerës së rritur ose rezultatit pozitiv.',
      low: 'Formulari i fotografuar nuk jep interpretim klinik të vlerës së ulët ose rezultatit negativ.',
      preparation: 'Përgatitja nuk është shënuar në formularin e fotografuar.',
      sourceLabel: source === 'analyzer' ? ANALYZER_SOURCE : FORM_SOURCE };
  };
  window.MEDINDEX_LABS = {
    version: '2026-07-23.2',
    language: 'sq',
    sourcePolicy: 'Vetëm analizat dhe intervalet që shihen në katër fotografitë e dërguara nga përdoruesja.',
    localBasis: 'Formularë laboratorikë të Ministrisë së Shëndetësisë së Kosovës (© 2008) dhe një printim i analizatorit hematologjik.',
    disclaimer: 'Vlerat dhe njësitë janë transkriptuar siç shihen në fotografi, pa korrigjim ose zëvendësim me burime të jashtme. Kur formulari dhe aparati japin intervale të ndryshme, të dyja shfaqen. Raporti aktual i laboratorit ka përparësi.',
    systems: [{"id":"hematologji","title":"Hematologjia","description":"Hemogrami, eritrocitet, leukocitet, trombocitet dhe indekset e aparatit."},{"id":"formula-leukocitare","title":"Formula leukocitare","description":"Përqindjet dhe grupet kryesore të leukociteve."},{"id":"koagulim","title":"Koagulimi","description":"PT, aPTT, TT, INR dhe fibrinogjeni."},{"id":"imunologji-serologji","title":"Imunologjia dhe serologjia","description":"Autoantitrupat, RF, ASTO, imunoglobulinat, komplementi dhe testet serologjike."},{"id":"melci-enzima","title":"Mëlçia dhe enzimat hepatobiliare","description":"Bilirubina, GGT, fosfataza alkaline, ALT dhe AST."},{"id":"muskuj-zemer-pankreas","title":"Muskujt, zemra dhe pankreasi","description":"CK, CK-MB, troponina, LDH, amilaza dhe fosfatazat."},{"id":"veshka-metabolizem","title":"Veshkat dhe metabolizmi","description":"Urea, kreatinina, glukoza dhe acidi urik."},{"id":"lipide-proteina","title":"Lipidet dhe proteinat","description":"Profili lipidik, proteinat totale, albumina dhe globulinat."},{"id":"elektrolite-minerale","title":"Elektrolitet dhe mineralet","description":"Natriumi, kaliumi, kloruret, magnezi, fosfori, kalciumi, lithiumi, hekuri dhe TIBC."},{"id":"urine","title":"Ekzaminimi i urinës","description":"Analizat kuantitative, kimike dhe sedimenti i urinës."},{"id":"toksikologji-infeksione","title":"Toksikologjia dhe infeksionet","description":"Skriningu urinar për substanca dhe Chlamydia trachomatis."},{"id":"fece","title":"Ekzaminimi i feçes","description":"Ekzaminimi i feçes sipas formularit të dërguar."}],
    tests: [
      ["esr","hematologji","Sedimentimi i eritrociteve","SE / ESR","Gjak i plotë","Meshkuj: deri 10; Femra: deri 15","mm/h","","","form"],
      ["rbc","hematologji","Numri i eritrociteve","RBC","Gjak EDTA","Meshkuj: 4.5–5.8; Femra: 3.8–4.9","×10¹²/L","Aparati në fotografinë e hemogramit: 3.50–5.50 ×10¹²/L","","form"],
      ["hgb","hematologji","Hemoglobina","HGB","Gjak EDTA","Meshkuj: 140–180; Femra: 120–160","g/L","Aparati në fotografinë e hemogramit: 115–165 g/L","","form"],
      ["wbc","hematologji","Numri i leukociteve","WBC","Gjak EDTA","4.0–8.0","×10⁹/L","Aparati në fotografinë e hemogramit: 3.5–10.0 ×10⁹/L","","form"],
      ["mcv","hematologji","Vëllimi mesatar eritrocitar","MCV","Gjak EDTA","81–94","fL","Aparati në fotografinë e hemogramit: 75.0–100.0 fL","","form"],
      ["mch","hematologji","Hemoglobina mesatare eritrocitare","MCH","Gjak EDTA","32–36","pg","Aparati në fotografinë e hemogramit: 25.0–35.0 pg","","form"],
      ["mchc","hematologji","Përqendrimi mesatar i hemoglobinës eritrocitare","MCHC","Gjak EDTA","310–350","g/L","Aparati në fotografinë e hemogramit: 310–380 g/L","","form"],
      ["hct","hematologji","Hematokriti","HCT","Gjak EDTA","35–45","%","Aparati në fotografinë e hemogramit: 35.0–55.0 %","","form"],
      ["plt","hematologji","Numri i trombociteve","PLT","Gjak EDTA","140–310","×10⁹/L","Aparati në fotografinë e hemogramit: 130–400 ×10⁹/L","","form"],
      ["retic","hematologji","Numri i retikulociteve","RET","Gjak EDTA","5–15","‰","","","form"],
      ["bleeding-time","hematologji","Koha e gjakderdhjes","","Gjak","2–3","min","","","form"],
      ["clotting-time","hematologji","Koha e ngjizjes","","Gjak","5–10","min","","","form"],
      ["peripheral-smear","hematologji","Lyerja periferike","","Gjak periferik","Nuk është shënuar në formular","","","","form"],
      ["lym-abs","hematologji","Limfocitet absolute","LYM","Gjak EDTA","0.9–5.0","×10⁹/L","","","analyzer"],
      ["lym-pct","formula-leukocitare","Limfocitet","LYM%","Gjak EDTA","15.0–50.0","%","","","analyzer"],
      ["mid-abs","hematologji","Qelizat MID absolute","MID","Gjak EDTA","0.1–1.5","×10⁹/L","","","analyzer"],
      ["mid-pct","formula-leukocitare","Qelizat MID","MID%","Gjak EDTA","2.0–15.0","%","","","analyzer"],
      ["gra-abs","hematologji","Granulocitet absolute","GRA","Gjak EDTA","1.2–8.0","×10⁹/L","","","analyzer"],
      ["gra-pct","formula-leukocitare","Granulocitet","GRA%","Gjak EDTA","35.0–80.0","%","","","analyzer"],
      ["rdw-a","hematologji","Gjerësia e shpërndarjes eritrocitare — absolute","RDW-a","Gjak EDTA","0.1–250.0","fL","","Intervali është transkriptuar saktësisht nga printimi i aparatit.","analyzer"],
      ["rdw-pct","hematologji","Gjerësia e shpërndarjes eritrocitare","RDW%","Gjak EDTA","11.0–16.0","%","","","analyzer"],
      ["mpv","hematologji","Vëllimi mesatar trombocitar","MPV","Gjak EDTA","6.5–11.0","fL","","","analyzer"],
      ["pdw-a","hematologji","Gjerësia e shpërndarjes trombocitare — absolute","PDW-a","Gjak EDTA","0.1–30.0","fL","","Intervali është transkriptuar saktësisht nga printimi i aparatit.","analyzer"],
      ["pdw-pct","hematologji","Gjerësia e shpërndarjes trombocitare","PDW%","Gjak EDTA","0.1–99.9","%","","Intervali është transkriptuar saktësisht nga printimi i aparatit.","analyzer"],
      ["pct","hematologji","Trombocitokriti","PCT","Gjak EDTA","0.01–9.99","%","","Intervali është transkriptuar saktësisht nga printimi i aparatit.","analyzer"],
      ["p-lcr","hematologji","Raporti i trombociteve të mëdha","P-LCR","Gjak EDTA","0.1–99.9","%","","Intervali është transkriptuar saktësisht nga printimi i aparatit.","analyzer"],
      ["p-lcc","hematologji","Numri i trombociteve të mëdha","P-LCC","Gjak EDTA","1–1999","×10⁹/L","","Intervali është transkriptuar saktësisht nga printimi i aparatit.","analyzer"],
      ["neutrophils","formula-leukocitare","Neutrofilet","NEUT","Gjak EDTA","54–62","%","","","form"],
      ["eosinophils","formula-leukocitare","Eozinofilet","EOS","Gjak EDTA","1–3","%","","","form"],
      ["basophils","formula-leukocitare","Bazofilet","BASO","Gjak EDTA","0–1","%","","","form"],
      ["lymphocytes","formula-leukocitare","Limfocitet","LYM","Gjak EDTA","25–33","%","","","form"],
      ["monocytes","formula-leukocitare","Monocitet","MONO","Gjak EDTA","3–7","%","","","form"],
      ["bands","formula-leukocitare","Të shkopëzuarat","","Gjak EDTA","0","%","","","form"],
      ["urea","veshka-metabolizem","Urea","UREA","Serum/plazmë","2.5–8.3","mmol/L","","","form"],
      ["creatinine-serum","veshka-metabolizem","Kreatinina","CREA","Serum/plazmë","Meshkuj: 70–108; Femra: 44–88","mmol/L","","Njësia është transkriptuar siç është shtypur në formular.","form"],
      ["glucose","veshka-metabolizem","Glukoza","GLU","Serum/plazmë","3.8–6.1","mmol/L","","","form"],
      ["cholesterol","lipide-proteina","Kolesteroli total","CHOL","Serum/plazmë","<6.5","mmol/L","","","form"],
      ["triglycerides","lipide-proteina","Trigliceridet","TG","Serum/plazmë","0.4–1.8","mmol/L","","","form"],
      ["total-lipids","lipide-proteina","Lipidet totale","","Serum/plazmë","4.5–10.5","mmol/L","","","form"],
      ["ldl","lipide-proteina","LDL kolesteroli","LDL","Serum/plazmë","3.9–4.9","mmol/L","","","form"],
      ["vldl","lipide-proteina","VLDL kolesteroli","VLDL","Serum/plazmë","Deri 0.9","mmol/L","","","form"],
      ["hdl","lipide-proteina","HDL kolesteroli","HDL","Serum/plazmë","Meshkuj: >1.42; Femra: >1.68","mmol/L","","","form"],
      ["uric-acid","veshka-metabolizem","Acidi urik","UA","Serum/plazmë","Meshkuj: 140–420; Femra: 90–350","","","Njësia nuk lexohet qartë në fotografinë e formularit.","form"],
      ["total-protein","lipide-proteina","Proteinat totale","","Serum/plazmë","65–83","g/L","","","form"],
      ["albumin","lipide-proteina","Albuminet","ALB","Serum/plazmë","35–53","g/L","","","form"],
      ["globulin","lipide-proteina","Globulinet","","Serum/plazmë","18–32","g/L","","","form"],
      ["fibrinogen","koagulim","Fibrinogjeni","FIB","Plazmë","2–4","g/L","","","form"],
      ["anti-dna","imunologji-serologji","Anti-n-DNA (Sist. Lup. Erythem.)","Anti-n-DNA","Serum","Negative","","","","form"],
      ["latex-rf","imunologji-serologji","Latex RF","RF","Serum","Negative","","","","form"],
      ["asto","imunologji-serologji","ASTO","ASTO","Serum","Deri 200","I.U./mL","","","form"],
      ["waler-rosse","imunologji-serologji","Waler Rosse","","Serum","Negative","","","","form"],
      ["crp","imunologji-serologji","CRP","CRP","Serum/plazmë","Deri 6","mg/L","","","form"],
      ["ggt","melci-enzima","γ-GT","GGT","Serum","Meshkuj: 8–37; Femra: 5–24","U/L","","","form"],
      ["bilirubin-total","melci-enzima","Bilirubina totale","BIL-T","Serum","5.0–20.0","mmol/L","","Njësia është transkriptuar siç është shtypur në formular.","form"],
      ["bilirubin-direct","melci-enzima","Bilirubina direkte","BIL-D","Serum","<7.0","mmol/L","","Njësia është transkriptuar siç është shtypur në formular.","form"],
      ["alp","melci-enzima","Fosfataza alkaline","ALP","Serum","Deri 15 vjeç: <644; Mbi 15 vjeç: 70–306","U/L","","","form"],
      ["alt","melci-enzima","ALT","ALT","Serum","<42","U/L","","","form"],
      ["ast","melci-enzima","AST","AST","Serum","<42","U/L","","","form"],
      ["ck","muskuj-zemer-pankreas","CK","CK","Serum","24–190","U/L","","","form"],
      ["ckmb","muskuj-zemer-pankreas","CK-MB","CK-MB","Serum","<25","U/L","","","form"],
      ["troponin-i","muskuj-zemer-pankreas","Troponina I","TnI","Serum/plazmë","Negative","","","","form"],
      ["ldh","muskuj-zemer-pankreas","LDH","LDH","Serum","225–450","U/L","","","form"],
      ["amylase-serum","muskuj-zemer-pankreas","α-Amilaza","AMY","Serum","Deri 220","U/L","","","form"],
      ["acid-phosphatase","muskuj-zemer-pankreas","Fosfataza acidike","","Serum","<6.5","U/L","","","form"],
      ["prostatic-phosphatase","muskuj-zemer-pankreas","Fosfataza prostatike","","Serum","<2.6","U/L","","","form"],
      ["sodium","elektrolite-minerale","Natriumi","Na","Serum/plazmë","136–146","mmol/L","","","form"],
      ["potassium","elektrolite-minerale","Kaliumi","K","Serum/plazmë","3.5–5.0","mmol/L","","","form"],
      ["chloride","elektrolite-minerale","Kloruret","Cl","Serum/plazmë","98–106","mmol/L","","","form"],
      ["magnesium","elektrolite-minerale","Magnezi","Mg","Serum","0.8–1.0","mmol/L","","","form"],
      ["phosphorus","elektrolite-minerale","Fosfori","P","Serum","Të rriturit: 0.81–1.62; Fëmijët: 1.30–2.26","mmol/L","","","form"],
      ["calcium","elektrolite-minerale","Kalciumi","Ca","Serum","2.02–2.60","mmol/L","","","form"],
      ["lithium","elektrolite-minerale","Lithiumi","Li","Serum","0.5–1.2","mmol/L","","","form"],
      ["iron","elektrolite-minerale","Hekuri (Fe++)","Fe","Serum","Meshkuj: 10.6–28.3; Femra: 6.6–26.0","mmol/L","","Njësia është transkriptuar siç është shtypur në formular.","form"],
      ["tibc","elektrolite-minerale","TIBC","TIBC","Serum","45–70","mg/dL","","","form"],
      ["iga","imunologji-serologji","IgA","IgA","Serum","90–450","mg/dL","","","form"],
      ["igg","imunologji-serologji","IgG","IgG","Serum","800–1800","mg/dL","","","form"],
      ["igm","imunologji-serologji","IgM","IgM","Serum","70–230","mg/dL","","","form"],
      ["c3","imunologji-serologji","C3","C3","Serum","75–135","mg/dL","","","form"],
      ["c4","imunologji-serologji","C4","C4","Serum","9–36","mg/dL","","","form"],
      ["syphilis-rpr","imunologji-serologji","Syphilis RPR test","RPR","Serum","Negative","","","","form"],
      ["syphilis-tpha","imunologji-serologji","Syphilis TPHA test","TPHA","Serum","Negative","","","","form"],
      ["pt","koagulim","Koha e protrombinës","PT","Plazmë citrat","70–120","%","","","form"],
      ["aptt","koagulim","Koha parciale e tromboplastinës","aPTT","Plazmë citrat","20.1–36.1","sek.","","","form"],
      ["tt","koagulim","Koha e trombinës","TT","Plazmë citrat","8–14","sek.","","","form"],
      ["inr","koagulim","INR (International Normalised Ratio)","INR","Plazmë citrat","Pacient pa terapi: 0.8–1.3; Pacient me terapi: 2–3.5","","","","form"],
      ["urine-amylase","urine","α-Amilaza në urinë","","Urinë","Urinë spontane: <400; Urinë 24 h: <1000","U/L","","","form"],
      ["urine-creatinine","urine","Kreatinina në urinë","","Urinë","56–74","mmol/min","","Njësia është transkriptuar siç është shtypur në formular.","form"],
      ["creatinine-clearance","urine","Klirensi i kreatininës","","Urinë 24 h + serum","96–144","mL/min","","","form"],
      ["urine-total-protein","urine","Proteinat totale në urinë","","Urinë","Deri 1.0","g/L","","","form"],
      ["bence-jones","urine","Proteinat Bence-Jones në urinë","","Urinë","Negative","","","","form"],
      ["thc-urine","toksikologji-infeksione","Kanabinoidet (THC) në urinë","THC","Urinë","Negative","","","","form"],
      ["cocaine-urine","toksikologji-infeksione","Cocaina (COC) në urinë","COC","Urinë","Negative","","","","form"],
      ["methamphetamine-urine","toksikologji-infeksione","Methamphetamina (MET) në urinë","MET","Urinë","Negative","","","","form"],
      ["opiates-urine","toksikologji-infeksione","Opiatet (OPI) në urinë","OPI","Urinë","Negative","","","","form"],
      ["amphetamine-urine","toksikologji-infeksione","AMPH (Amfetamina)","AMPH","Urinë","Negative","","","","form"],
      ["ecstasy-urine","toksikologji-infeksione","ECS (Ecstasy)","ECS","Urinë","Negative","","","","form"],
      ["chlamydia","toksikologji-infeksione","Chlamydia trachomatis","","Mostra sipas laboratorit","Negative","","","","form"],
      ["urine-appearance","urine","Pamja","","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["urine-color","urine","Ngjyra","","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["urine-reaction","urine","Reaksioni","pH","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["urine-specific-gravity","urine","Pesha specifike","SG","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["urine-protein","urine","Proteinet","PRO","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["urine-glucose","urine","Glukoza","GLU","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["urine-blood","urine","Gjaku","BLD","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["urine-ketones","urine","Acetoni","KET","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["urine-bilirubin","urine","Bilirubina","BIL","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["urine-urobilinogen","urine","Urobilinogjeni","URO","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["urine-nitrite","urine","Nitritet","NIT","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["urine-sediment","urine","Sedimenti","","Urinë","Nuk është shënuar në formular","","","Vlera referente nuk është dhënë në fotografinë e formularit.","form"],
      ["stool-exam","fece","Ekzaminimi i feçes","","Feçe","Nuk është shënuar në formular","","","Nën-analizat dhe vlerat referente nuk janë dhënë në fotografinë e formularit.","form"]
    ].map(make)
  };
})();
