window.MEDINDEX_LABS = {
  version: '2026-07-23.1',
  localBasis: 'Analizat bazë të ofruara nga QKMF Prishtinë dhe njësitë SI të përdorura zakonisht në Kosovë.',
  localSourceUrl: 'https://qkmf-pr.org/sq/laboratoriumi',
  disclaimer: 'Intervalet janë orientuese për të rritur. Intervali i shtypur në raportin e laboratorit ka përparësi, sepse ndryshon sipas metodës, aparaturës, moshës, gjinisë, shtatzënisë dhe laboratorit.',
  systems: [
    { id:'hematologji', title:'Hematologjia', description:'Hemogrami dhe qelizat e gjakut.' },
    { id:'inflamacion-hekur', title:'Inflamacioni dhe statusi i hekurit', description:'CRP, sedimentimi, ferritina dhe vitaminat hematopoetike.' },
    { id:'veshka-elektrolite', title:'Veshkat dhe elektrolitet', description:'Filtrimi renal, urea dhe ekuilibri elektrolitik.' },
    { id:'melcia', title:'Mëlçia dhe proteinat', description:'Dëmtimi hepatocelular, kolestaza dhe sinteza hepatike.' },
    { id:'diabet-metabolizem', title:'Diabeti dhe metabolizmi', description:'Glikemia, HbA1c, kalciumi dhe acidi urik.' },
    { id:'lipide', title:'Lipidet dhe rreziku kardiovaskular', description:'Kolesteroli, HDL, LDL dhe trigliceridet.' },
    { id:'tiroide', title:'Gjëndra tiroide', description:'TSH dhe hormonet e lira tiroide.' },
    { id:'urine', title:'Urina', description:'Skriningu kimik dhe sedimentimi i urinës.' }
  ],
  tests: [
    {id:'hb',system:'hematologji',name:'Hemoglobina',abbr:'Hb',specimen:'Gjak EDTA',reference:'Meshkuj 130–180; Femra 115–165',unit:'g/L',kosovoCore:true,why:'Vlerëson aneminë, policiteminë dhe kapacitetin transportues të oksigjenit.',high:'Dehidratim, hipoksi kronike ose policitemi; interpretohet me hematokritin dhe eritrocitet.',low:'Anemi nga mungesa e hekurit/B12/folatit, humbje gjaku, sëmundje kronike ose hemolizë.',preparation:'Nuk kërkon esëll.',sourceUrl:'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/haematology/haematology-reference-ranges/'},
    {id:'wbc',system:'hematologji',name:'Leukocitet totale',abbr:'WBC',specimen:'Gjak EDTA',reference:'3.6–11.0',unit:'×10⁹/L',kosovoCore:true,why:'Vlerëson infeksionin, inflamacionin dhe çrregullimet hematologjike.',high:'Infeksion bakterial, inflamacion, kortikosteroide, stres fiziologjik ose sëmundje mieloproliferative.',low:'Infeksion viral, barna, insuficiencë medulare ose sëmundje autoimune.',preparation:'Nuk kërkon esëll.',sourceUrl:'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/haematology/haematology-reference-ranges/'},
    {id:'neut',system:'hematologji',name:'Neutrofilet absolute',abbr:'NEUT',specimen:'Gjak EDTA',reference:'1.8–7.5',unit:'×10⁹/L',kosovoCore:true,why:'Ndihmon në vlerësimin e infeksioneve bakteriale dhe neutropenisë.',high:'Infeksion bakterial, inflamacion, stres ose kortikosteroide.',low:'Infeksion viral, kimioterapi/barna, sepsë e rëndë ose insuficiencë medulare.',preparation:'Interpretohet bashkë me WBC dhe formulën leukocitare.',sourceUrl:'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/haematology/haematology-reference-ranges/'},
    {id:'lymph',system:'hematologji',name:'Limfocitet absolute',abbr:'LYMPH',specimen:'Gjak EDTA',reference:'1.0–4.0',unit:'×10⁹/L',kosovoCore:true,why:'Vlerëson përgjigjen imune, infeksionet virale dhe çrregullimet limfoproliferative.',high:'Infeksione virale ose çrregullime limfoproliferative.',low:'Kortikosteroide, imunodeficiencë, stres i rëndë ose kimioterapi.',preparation:'Nuk kërkon esëll.',sourceUrl:'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/haematology/haematology-reference-ranges/'},
    {id:'plt',system:'hematologji',name:'Trombocitet',abbr:'PLT',specimen:'Gjak EDTA',reference:'140–400',unit:'×10⁹/L',kosovoCore:true,why:'Vlerëson rrezikun e gjakderdhjes dhe trombocitozën.',high:'Inflamacion, mungesë hekuri, pas splenektomisë ose sëmundje mieloproliferative.',low:'Infeksione, barna, ITP, DIC, hipersplenizëm ose insuficiencë medulare.',preparation:'Pseudotrombocitopenia nga grumbullimi në EDTA kërkon kontroll të mostrës.',sourceUrl:'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/haematology/haematology-reference-ranges/'},
    {id:'rbc',system:'hematologji',name:'Eritrocitet',abbr:'RBC',specimen:'Gjak EDTA',reference:'Meshkuj 4.50–6.50; Femra 3.80–5.80',unit:'×10¹²/L',kosovoCore:true,why:'Pjesë e vlerësimit të anemisë dhe eritrocitozës.',high:'Dehidratim, hipoksi kronike ose policitemi.',low:'Anemi, humbje gjaku ose insuficiencë medulare.',preparation:'Interpretohet me Hb, Hct dhe indeksat eritrocitarë.',sourceUrl:'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/haematology/haematology-reference-ranges/'},
    {id:'hct',system:'hematologji',name:'Hematokriti',abbr:'Hct',specimen:'Gjak EDTA',reference:'Meshkuj 0.40–0.54; Femra 0.37–0.47',unit:'L/L',kosovoCore:true,why:'Tregon pjesën e volumit të gjakut të zënë nga eritrocitet.',high:'Dehidratim ose eritrocitozë.',low:'Anemi, gjakderdhje ose hemodilucion.',preparation:'Gjendja e hidratimit ndikon në rezultat.',sourceUrl:'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/haematology/haematology-reference-ranges/'},
    {id:'mcv',system:'hematologji',name:'Vëllimi mesatar eritrocitar',abbr:'MCV',specimen:'Gjak EDTA',reference:'80–100',unit:'fL',kosovoCore:true,why:'Klasifikon aneminë si mikrocitare, normocitare ose makrocitare.',high:'Mungesë B12/folati, alkool, sëmundje hepatike, hipotiroidizëm ose barna.',low:'Mungesë hekuri, talasemi ose anemi e sëmundjes kronike.',preparation:'Interpretohet me MCH, RDW, ferritinën dhe retikulocitet.',sourceUrl:'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/haematology/haematology-reference-ranges/'},

    {id:'crp',system:'inflamacion-hekur',name:'Proteina C-reaktive',abbr:'CRP',specimen:'Serum/plazmë',reference:'<5',unit:'mg/L',kosovoCore:false,why:'Marker i shpejtë i inflamacionit dhe infeksionit; përdoret edhe për monitorim të trendit.',high:'Infeksion, inflamacion, dëmtim indor ose sëmundje autoimune; nuk përcakton vetë shkakun.',low:'Vlera e ulët nuk e përjashton gjithmonë sëmundjen, sidomos herët në proces.',preparation:'Nuk kërkon esëll; trendi është shpesh më informues se një vlerë e vetme.',sourceUrl:'https://pathology.uhsussex.nhs.uk/pug/?catid=10&id=210&view=article'},
    {id:'esr',system:'inflamacion-hekur',name:'Shpejtësia e sedimentimit të eritrociteve',abbr:'SE / ESR',specimen:'Gjak i plotë',reference:'<50 vj: M 1–7, F 3–9; ≥50 vj: M 2–10, F 5–15',unit:'mm/orë',kosovoCore:true,why:'Marker jo specifik për inflamacion kronik, infeksion, anemi ose sëmundje autoimune.',high:'Inflamacion, infeksion, anemi, shtatzëni ose paraproteinemi.',low:'Zakonisht me rëndësi të kufizuar; mund të shihet në policitemi ose forma jonormale eritrocitare.',preparation:'Interpretohet sipas moshës/gjinisë dhe bashkë me CRP.',sourceUrl:'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/haematology/haematology-reference-ranges/'},
    {id:'ferritin',system:'inflamacion-hekur',name:'Ferritina',abbr:'Ferritin',specimen:'Serum',reference:'Meshkuj 24–340; Femra 11–310',unit:'µg/L',kosovoCore:false,why:'Vlerëson rezervat e hekurit dhe është testi kryesor për mungesën e hekurit.',high:'Inflamacion, sëmundje hepatike, mbingarkesë me hekur ose malignitet; është proteinë e fazës akute.',low:'Mungesë hekuri derisa të dëshmohet e kundërta.',preparation:'CRP ndihmon në interpretim kur dyshohet inflamacion.',sourceUrl:'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/tests-and-investigations/ferritin-assay/'},
    {id:'b12',system:'inflamacion-hekur',name:'Vitamina B12',abbr:'B12',specimen:'Serum',reference:'180–914 normal; 145–179 kufitare; ≤144 e ulët',unit:'ng/L',kosovoCore:false,why:'Vlerëson mungesën e B12 në anemi makrocitare dhe simptoma neurologjike.',high:'Suplementim, sëmundje hepatike/renale ose çrregullime mieloproliferative; interpretohet klinikisht.',low:'Mungesë B12 nga dietë, malabsorbim, anemi pernicioze ose barna.',preparation:'Vlera kufitare mund të kërkojë teste plotësuese sipas laboratorit.',sourceUrl:'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/haematology/haematology-reference-ranges/'},

    {id:'creatinine',system:'veshka-elektrolite',name:'Kreatinina',abbr:'CREA',specimen:'Serum/plazmë',reference:'Meshkuj 64–104; Femra 49–90',unit:'µmol/L',kosovoCore:true,why:'Vlerëson filtrimin renal dhe përdoret për llogaritjen e eGFR.',high:'Ulja e filtrimit renal, dehidratim, obstruksion, rabdomiolizë ose masë e madhe muskulore.',low:'Masë e ulët muskulore, shtatzëni ose hemodilucion; jo domosdoshmërisht sëmundje.',preparation:'Interpretohet me eGFR, moshën, masën muskulore dhe trendin.',sourceUrl:'https://www.ruh.nhs.uk/pathology/blood_test_info/tubelisting.asp?id=362&listing=u'},
    {id:'egfr',system:'veshka-elektrolite',name:'Shkalla e vlerësuar e filtrimit glomerular',abbr:'eGFR',specimen:'Llogaritet nga kreatinina',reference:'≥60',unit:'mL/min/1.73m²',kosovoCore:true,why:'Kategorizon funksionin renal dhe ndihmon në dozimin e barnave.',high:'Vlera e lartë zakonisht nuk është problem; hiperfiltrimi mund të kërkojë kontekst klinik.',low:'Mund të tregojë sëmundje kronike/akute renale; CKD kërkon persistencë ose markerë tjerë të dëmtimit.',preparation:'Formula e të rriturve nuk përdoret te fëmijët; përsërit dhe interpreto trendin.',sourceUrl:'https://www.mayocliniclabs.com/test-catalog/Overview/48216'},
    {id:'urea',system:'veshka-elektrolite',name:'Urea',abbr:'UREA',specimen:'Serum/plazmë',reference:'2.5–7.8',unit:'mmol/L',kosovoCore:true,why:'Vlerëson metabolizmin e proteinave, hidratimin dhe funksionin renal.',high:'Dehidratim, dështim renal, gjakderdhje gastrointestinale ose katabolizëm i shtuar.',low:'Marrje e ulët proteinash, sëmundje e rëndë hepatike ose mbihidratim.',preparation:'Interpretohet bashkë me kreatininën dhe gjendjen e hidratimit.',sourceUrl:'https://www.ruh.nhs.uk/pathology/blood_test_info/tubelisting.asp?id=362&listing=u'},
    {id:'sodium',system:'veshka-elektrolite',name:'Natriumi',abbr:'Na',specimen:'Serum/plazmë',reference:'135–145',unit:'mmol/L',kosovoCore:false,why:'Vlerëson ekuilibrin e ujit dhe osmolalitetin.',high:'Humbje uji, diabet insipid ose ngarkesë natriumi.',low:'SIADH, diuretikë, insuficiencë kardiake/hepatike, humbje gastrointestinale ose mbingarkesë me ujë.',preparation:'Korrigjohet/analizohet me glukozën, osmolalitetin dhe statusin volumor.',sourceUrl:'https://www.mayocliniclabs.com/test-catalog/overview/113630'},
    {id:'potassium',system:'veshka-elektrolite',name:'Kaliumi',abbr:'K',specimen:'Serum/plazmë',reference:'3.6–5.2',unit:'mmol/L',kosovoCore:false,why:'Kritik për ritmin kardiak dhe funksionin neuromuskular.',high:'Dështim renal, barna, acidozë ose hemolizë e mostrës; vlerat e larta mund të jenë urgjencë.',low:'Diuretikë, humbje gastrointestinale, alkalozë ose hiperaldosteronizëm.',preparation:'Kontrollo hemolizën dhe përsërit urgjent kur rezultati nuk përputhet me klinikën.',sourceUrl:'https://www.mayocliniclabs.com/test-catalog/overview/113630'},

    {id:'alt',system:'melcia',name:'Alanine aminotransferaza',abbr:'ALT',specimen:'Serum/plazmë',reference:'Meshkuj <41; Femra <34',unit:'U/L',kosovoCore:true,why:'Marker relativisht specifik i dëmtimit hepatocelular.',high:'Hepatit, steatohepatit, barna/toksina ose dëmtim muskulor; madhësia nuk tregon gjithmonë severitetin funksional.',low:'Zakonisht pa rëndësi klinike.',preparation:'Interpretohet me AST, bilirubinën, ALP/GGT dhe historinë e barnave/alkoolit.',sourceUrl:'https://www.easternpathologyalliance.nhs.uk/tests/alanine-aminotransferase-alt/'},
    {id:'ast',system:'melcia',name:'Aspartate aminotransferaza',abbr:'AST',specimen:'Serum/plazmë',reference:'Meshkuj 10–50; Femra 10–35',unit:'U/L',kosovoCore:true,why:'Vlerëson dëmtimin hepatik, por gjendet edhe në muskuj dhe organe tjera.',high:'Dëmtim hepatik ose muskulor, hemolizë, ishemi ose alkool; krahaso me ALT dhe CK.',low:'Zakonisht pa rëndësi klinike.',preparation:'Hemoliza mund ta rrisë rezultatin.',sourceUrl:'https://www.nwangliaft.nhs.uk/pathology-requesting-and-reporting-updates/'},
    {id:'bilirubin',system:'melcia',name:'Bilirubina totale',abbr:'BILI-T',specimen:'Serum/plazmë',reference:'<21',unit:'µmol/L',kosovoCore:true,why:'Vlerëson verdhëzën, hemolizën, konjugimin hepatik dhe obstruksionin biliar.',high:'Hemolizë, hepatit, sindromë Gilbert ose kolestazë; fraksionet direkte/indirekte e orientojnë shkakun.',low:'Pa rëndësi klinike.',preparation:'Interpretohet me bilirubinën direkte, ALT/AST, ALP/GGT dhe hemogramin.',sourceUrl:'https://www.waht.nhs.uk/Documents/Blood%20Sciences%20User%20Guide%20PDF.pdf'},
    {id:'albumin',system:'melcia',name:'Albumina',abbr:'ALB',specimen:'Serum',reference:'35–52',unit:'g/L',kosovoCore:false,why:'Vlerëson sintezën hepatike, gjendjen ushqyese dhe humbjen renale/enterale të proteinave.',high:'Kryesisht dehidratim.',low:'Inflamacion, sëmundje hepatike, sindromë nefrotike, kequshqyerje ose humbje enterale.',preparation:'Është marker i ngadalshëm dhe ndikohet nga inflamacioni/volumi.',sourceUrl:'https://pathology.uhsussex.nhs.uk/pug/biochemistry-immunology/biochemistry-tests/107-albumin-serum'},

    {id:'glucose',system:'diabet-metabolizem',name:'Glikemia esëll',abbr:'GLU',specimen:'Plazmë/serum',reference:'3.0–5.4',unit:'mmol/L',kosovoCore:true,why:'Skrining dhe diagnozë e çrregullimeve të glukozës.',high:'6.1–6.9 mmol/L sugjeron glikemi të dëmtuar esëll; ≥7.0 mmol/L kërkon vlerësim diagnostik dhe zakonisht konfirmim kur pacienti është pa simptoma.',low:'Hipoglikemia kërkon vlerësim sipas simptomave, barnave dhe kohës së mostrës.',preparation:'8–12 orë esëll, vetëm ujë; shëno kohën e fundit të ushqimit dhe barnat.',sourceUrl:'https://pathology.royalcornwallhospitals.nhs.uk/viewTest.php?ID=208'},
    {id:'hba1c',system:'diabet-metabolizem',name:'Hemoglobina e glikuar',abbr:'HbA1c',specimen:'Gjak EDTA',reference:'25–41',unit:'mmol/mol',kosovoCore:false,why:'Tregon glikeminë mesatare të rreth 2–3 muajve dhe përdoret për diagnozë/monitorim të diabetit.',high:'42–47 mmol/mol rrezik i lartë; ≥48 mmol/mol është prag diagnostik që te pacienti pa simptoma kërkon konfirmim.',low:'Mund të jetë artificialisht e ulët kur jetëgjatësia e eritrociteve është e shkurtuar.',preparation:'Nuk kërkon esëll; hemoglobinopatitë, anemia, transfuzioni dhe shtatzënia mund ta shtrembërojnë.',sourceUrl:'https://www.uhd.nhs.uk/services/pathology/haematology/test-repertoire-and-reference-ranges'},
    {id:'calcium',system:'diabet-metabolizem',name:'Kalciumi total',abbr:'Ca',specimen:'Serum/plazmë',reference:'2.20–2.60',unit:'mmol/L',kosovoCore:false,why:'Vlerëson metabolizmin kockor, paratiroidet dhe çrregullimet elektrolitike.',high:'Hiperparatiroidizëm, malignitet, vitamina D ose barna.',low:'Mungesë vitamine D, hipoparatiroidizëm, insuficiencë renale ose albuminë e ulët.',preparation:'Korrigjo për albuminën ose përdor kalciumin jonizues kur është e nevojshme.',sourceUrl:'https://www.waht.nhs.uk/Documents/Blood%20Sciences%20User%20Guide%20PDF.pdf'},
    {id:'urate',system:'diabet-metabolizem',name:'Acidi urik / urati',abbr:'UA',specimen:'Serum/plazmë',reference:'Meshkuj 200–430; Femra 190–360',unit:'µmol/L',kosovoCore:false,why:'Vlerëson hiperuriceminë, përdhesin dhe rrezikun nga lizimi qelizor.',high:'Përdhes, insuficiencë renale, diuretikë, alkool, sindromë metabolike ose lizë tumorale.',low:'Barna urikozurike, marrje e ulët purinash ose çrregullime të rralla metabolike.',preparation:'Vlera gjatë sulmit akut të përdhesit mund të jetë normale; përsërite pas qetësimit.',sourceUrl:'https://www.waht.nhs.uk/Documents/Blood%20Sciences%20User%20Guide%20PDF.pdf'},

    {id:'chol',system:'lipide',name:'Kolesteroli total',abbr:'CHOL',specimen:'Serum/plazmë',reference:'<5.0',unit:'mmol/L',kosovoCore:true,why:'Pjesë e vlerësimit të rrezikut kardiovaskular.',high:'Rreziku interpretohet me LDL, HDL, trigliceridet, moshën dhe faktorët klinikë.',low:'Mund të shihet në kequshqyerje, hipertiroidizëm ose sëmundje të rënda, por zakonisht nuk vlerësohet i vetëm.',preparation:'Profili lipidik shpesh mund të bëhet jo esëll; esëll ndihmon kur trigliceridet janë të larta.',sourceUrl:'https://www.nhs.uk/conditions/high-cholesterol/cholesterol-levels/'},
    {id:'hdl',system:'lipide',name:'HDL-kolesteroli',abbr:'HDL',specimen:'Serum/plazmë',reference:'Meshkuj >1.0; Femra >1.2',unit:'mmol/L',kosovoCore:false,why:'Pjesë e vlerësimit të rrezikut kardiovaskular dhe raportit total/HDL.',high:'Zakonisht lidhet me rrezik më të ulët, por nuk interpretohet i izoluar.',low:'Lidhet me rrezik më të lartë kardiometabolik.',preparation:'Interpretohet me profilin e plotë dhe rrezikun global.',sourceUrl:'https://www.nhs.uk/conditions/high-cholesterol/cholesterol-levels/'},
    {id:'ldl',system:'lipide',name:'LDL-kolesteroli',abbr:'LDL',specimen:'Serum/plazmë',reference:'Objektiv orientues <2.6; objektivi real varet nga rreziku',unit:'mmol/L',kosovoCore:false,why:'Objektivi kryesor i trajtimit lipidik dhe vlerësimit të rrezikut aterosklerotik.',high:'Rrit rrezikun aterosklerotik; objektivat janë shumë më të ulëta te pacientët me rrezik të lartë.',low:'Zakonisht i dëshirueshëm në kontekst të trajtimit, por vlerësohet klinikisht.',preparation:'Mund të jetë i llogaritur dhe më pak i saktë kur trigliceridet janë shumë të larta.',sourceUrl:'https://www.mayocliniclabs.com/test-catalog/overview/616727'},
    {id:'tg',system:'lipide',name:'Trigliceridet',abbr:'TG',specimen:'Serum/plazmë',reference:'<1.7 esëll',unit:'mmol/L',kosovoCore:true,why:'Vlerëson dislipideminë dhe rrezikun e pankreatitit kur janë shumë të larta.',high:'Diabet i pakontrolluar, alkool, obezitet, barna, hipotiroidizëm ose çrregullim gjenetik.',low:'Zakonisht pa rëndësi klinike.',preparation:'Për rezultat të lartë ose vlerësim të plotë mund të kërkohet 10–12 orë esëll.',sourceUrl:'https://pathology.royalcornwallhospitals.nhs.uk/viewTest.php?ID=273'},

    {id:'tsh',system:'tiroide',name:'Hormoni stimulues i tiroides',abbr:'TSH',specimen:'Serum',reference:'0.35–4.94',unit:'mIU/L',kosovoCore:false,why:'Testi fillestar kryesor për funksionin e tiroides.',high:'Hipotiroidizëm primar ose dozë e pamjaftueshme e levotiroksinës; interpretohet me FT4.',low:'Hipertiroidizëm, dozë e tepërt e hormonit ose shtypje nga sëmundje/barna.',preparation:'Shtatzënia ka intervale specifike; biotina mund të interferojë me disa metoda.',sourceUrl:'https://www.easternpathologyalliance.nhs.uk/tests/thyroid-stimulating-hormone-tsh/'},
    {id:'ft4',system:'tiroide',name:'Tiroksina e lirë',abbr:'FT4',specimen:'Serum',reference:'11.6–21.9 (ekuivalent me 0.9–1.7 ng/dL)',unit:'pmol/L',kosovoCore:false,why:'Konfirmon dhe klasifikon çrregullimin tiroide bashkë me TSH.',high:'Hipertiroidizëm ose dozë e tepërt e levotiroksinës.',low:'Hipotiroidizëm ose sëmundje e rëndë jo-tiroide; vlerëso me TSH dhe kontekstin.',preparation:'Metoda, shtatzënia, proteinat lidhëse dhe biotina mund të ndikojnë.',sourceUrl:'https://origin.mayocliniclabs.com/test-catalog/overview/8725'},

    {id:'urinalysis',system:'urine',name:'Analiza e plotë e urinës',abbr:'Urina komplet',specimen:'Urina e mesit të rrjedhës',reference:'Leukocite, nitrite, proteinë, glukozë, ketone dhe gjak: zakonisht negative',unit:'cilësore / sipas analizatorit',kosovoCore:true,why:'Skrining për infeksion urinar, proteinuri, hematuri, glukozuri dhe çrregullime metabolike.',high:'Rezultati pozitiv orientohet sipas parametrit; kërkon korrelacion me sedimentin, simptomat dhe kulturën.',low:'Rezultati negativ nuk e përjashton gjithmonë infeksionin ose sëmundjen renale.',preparation:'Mostër e pastër e mesit të rrjedhës; dorëzohet shpejt. Menstruacionet dhe kontaminimi ndikojnë.',sourceUrl:'https://qkmf-pr.org/sq/laboratoriumi'}
  ]
};