-- Synced from Supabase production migration history.
-- version: 20260827094417
-- name: seed_substance_aliases_reviewed

insert into public.substance_aliases (variant_key, canonical_key, reason, canonical_name, decided_by) values
-- Gabime shtypi
('bethamethasonedipropionate','betamethasonedipropionate','gabim shtypi','',''),
('bethametasonedipropionate','betamethasonedipropionate','gabim shtypi','',''),
('ampicilintrihydrateequivalenttoapicilin','ampicillintrihydrateequivalenttoapicillin','gabim shtypi','',''),
('budesonideformoterolfumaratedihhydrate','budesonideformoterolfumaratedihydrate','gabim shtypi','',''),
('articainehydrochlorideadrenalineepinephrinetartarate','articainehydrochlorideadrenalineepinephrinetartrate','gabim shtypi','',''),
('amiodaronehydrochlorid','amiodaronehydrochloride','gabim shtypi','',''),
('verapamilhydrochlorid','verapamilhydrochloride','gabim shtypi','',''),
('levofloxacinhemihydrates','levofloxacinhemihydrate','gabim shtypi','',''),
('levofloxacinehemihydrate','levofloxacinhemihydrate','gabim shtypi','',''),
('pantoprazolesodiumsesquilhydrate','pantoprazolesodiumsesquihydrate','gabim shtypi','',''),
('cefepimedihydrochlridemonohydrate','cefepimedihydrochloridemonohydrate','gabim shtypi','',''),
('zolendronicacidmonohydrate','zoledronicacidmonohydrate','gabim shtypi','',''),
('zolendronicacidasmonohydrate','zoledronicacidmonohydrate','gabim shtypi','',''),
('lercanidipinhydrochloride','lercanidipinehydrochloride','gabim shtypi','',''),
('amoxillintrihydrate','amoxicillintrihydrate','gabim shtypi','',''),
('vasartanhydrochlorothiazide','valsartanhydrochlorothiazide','gabim shtypi','',''),
('oxymethazolinehydrochloride','oxymetazolinehydrochloride','gabim shtypi','',''),
('oxymethazolinehydrocloride','oxymetazolinehydrochloride','gabim shtypi','',''),
('ciprofloxacinehydrochloride','ciprofloxacinhydrochloride','gabim shtypi','',''),
('ciprofloxacinhidrochloride','ciprofloxacinhydrochloride','gabim shtypi','',''),
('nebivololhydrocloride','nebivololhydrochloride','gabim shtypi','',''),
('rosuvastincalcium','rosuvastatincalcium','gabim shtypi','',''),
('rosuvastatininformof10396mgofrosuvastatinecalcium','rosuvastatininformof10396mgofrosuvastatincalcium','gabim shtypi','',''),
('metoprololtartarate','metoprololtartrate','gabim shtypi','',''),
('levocetirizinadihydrochloride','levocetirizinedihydrochloride','gabim shtypi','',''),
('levoceterizinedihydrochloride','levocetirizinedihydrochloride','gabim shtypi','',''),
('betahistinedihidrochloride','betahistinedihydrochloride','gabim shtypi','',''),
('chlorpyraminehydrochloride','chloropyraminehydrochloride','gabim shtypi','',''),
('isoconasolenitratediflucortolonevalerate','isoconazolenitratediflucortolonevalerate','gabim shtypi','',''),
('mometazonefuroatemonohydrate','mometasonefuroatemonohydrate','gabim shtypi','',''),
('amlodipineasamlodipinebesiliate','amlodipineasamlodipinebesilate','gabim shtypi','',''),
('empaglifozinmetforminhydrochloride','empagliflozinmetforminhydrochloride','gabim shtypi','',''),
('lisinoprildehydratehydrochlorothiazide','lisinoprildihydratehydrochlorothiazide','gabim shtypi','',''),
('losartanpotassiumhydrochlorotiazide','losartanpotassiumhydrochlorothiazide','gabim shtypi','',''),
('losartanpotassiumhydrochlorthiazide','losartanpotassiumhydrochlorothiazide','gabim shtypi','',''),
('amoxicillinandclavulatepotassium71','amoxicillinandclavulantepotassium71','gabim shtypi','',''),
('paracetamolpseudoephedrinehclchlorpheniraminemaleat','paracetamolpseudoephedrinehclchlorpheniraminemaleate','gabim shtypi','',''),
('paracetamolpseudoephrdrinehydrochloridechlorphenaminemaleat','paracetamolpseudoephedrinehydrochloridechlorpheniraminemaleate','gabim shtypi','',''),
('heparinsodiumprednisoloneacetatepolydocanol','heparinsodiumprednisoloneacetatepolidocanol','gabim shtypi','',''),
('peridonpriltertbutyamine','peridonpriltertbutylamine','gabim shtypi','',''),
('lysozymehydrochloridecetylpiridiniumchloride','lysozymehydrochloridecetylpyridiniumchloride','gabim shtypi','',''),
('valsartanamplodipinebesylatehydrochlorthiazide','valsartanamlodipinebesylatehydrochlorothiazide','gabim shtypi','',''),
('amlodipinemesilatemonyhydrate','amlodipinemesilatemonohydrate','gabim shtypi','',''),
('imipenemmonohydrateequivalenttoimpenemcilastatinsodiumequivalntetocilastatin','imipenemmonohydrateequivalenttoimipenemcilastatinsodiumequivalenttocilastatin','gabim shtypi','',''),
('chloramphenicolmetronidazolenystatinehydrocortizoneacetate','chloramphenicolmetronidazolnystatinehydrocortisoneacetate','gabim shtypi','',''),
-- Mbaresa e ndryshme e të njëjtit emër (INN kundrejt formës vendore)
('bisoprololfumarat','bisoprololfumarate','mbaresë e ndryshme','',''),
('flecainideacetat','flecainideacetate','mbaresë e ndryshme','',''),
('tofacitinibcitrat','tofacitinibcitrate','mbaresë e ndryshme','',''),
('sodiumvalproat','sodiumvalproate','mbaresë e ndryshme','',''),
('dimenhydrinat','dimenhydrinate','mbaresë e ndryshme','',''),
('pentoxifyllin','pentoxifylline','mbaresë e ndryshme','',''),
('cyanocobalamin','cyanocobalamine','mbaresë e ndryshme','',''),
('silversulfadiazin','silversulfadiazine','mbaresë e ndryshme','',''),
('ketorolactrometamolo','ketorolactrometamol','mbaresë e ndryshme','',''),
('quifenadinihydrochloridum','quifenadinihydrochloride','mbaresë e ndryshme','',''),
('dutasteridetamsulosinehydrochloride','dutasteridetamsulosinhydrochloride','mbaresë e ndryshme','',''),
('paracetamolcodeinephosphatehemihydrate','paracetamolcodeinphosphatehemihydrate','mbaresë e ndryshme','',''),
('metronidazolclotrimazol','metronidazoleclotrimazole','mbaresë e ndryshme','',''),
('metronidazolclotrimazole','metronidazoleclotrimazole','mbaresë e ndryshme','',''),
('amoxycillinetrihydratepotassiumclavulanate','amoxicillintrihydratepotassiumclavulanate','mbaresë e ndryshme','',''),
('amoxycillintrihydratepotassiumclavulanate','amoxicillintrihydratepotassiumclavulanate','mbaresë e ndryshme','',''),
('perindoprilterbutylamine','perindopriltertbutylamine','mbaresë e ndryshme','',''),
('fluocinoloneacetonideneomycinsulphate','fluocinoloneacetonideneomycinsulfate','sulfate/sulphate','',''),
-- Emra alternativë të pranuar për të njëjtën substancë
('paracetamolpseudoephedrinehydrochloridechlorphenaminemaleate','paracetamolpseudoephedrinehydrochloridechlorpheniraminemaleate','chlorphenamine = chlorpheniramine','',''),
('paracetamolhyoscinebutylbromide','paracetamolhyoscinenbutylbromide','hyoscine butylbromide = N-butylbromide','',''),
('isosorbide5mononitrate','isosorbidemononitrate','isosorbid-5-mononitrat = isosorbid mononitrat','',''),
('humanantitetanusimmunoglobulin','humantetanusimmunoglobulin','emër alternativ','',''),
('amlodipinebesylateequivalenttoamlodipine','amlodipinebesilateequivalenttoamlodipine','besylate = besilate','',''),
('amlodipinebesylatevalsartanhydrochlorothiazide','amlodipinebesilatevalsartanhydrochlorothiazide','besylate = besilate','',''),
-- Shtesa pa vlerë dalluese: farmakope, forma e njëjtë e shprehur ndryshe
('diclofenacsodiumbp','diclofenacsodium','shtesë farmakopeje','',''),
('ampicillinsodiumbp','ampicillinsodium','shtesë farmakopeje','',''),
('pantoprazolesodiumbp','pantoprazolesodium','shtesë farmakopeje','',''),
('colistimethatesodiumusp','colistimethatesodium','shtesë farmakopeje','',''),
('adrenalineacidtartratebp','adrenalineacidtartrate','shtesë farmakopeje','',''),
('azithromycininndihydrate','azithromycindihydrate','shtesë farmakopeje','',''),
('gentamicingentamicinsulfate','gentamicinsulfate','e njëjta formë, shprehur ndryshe','',''),
('moxifloxacinasmoxifloxacinhydrochloride','moxifloxacinhydrochloride','e njëjta formë, shprehur ndryshe','',''),
('moxifloxacinashydrochloride','moxifloxacinhydrochloride','e njëjta formë, shprehur ndryshe','',''),
('ceftriaxoneasceftriaxonesodium','ceftriaxonesodium','e njëjta formë, shprehur ndryshe','',''),
('ampicillinasampicillinsodium','ampicillinsodium','e njëjta formë, shprehur ndryshe','',''),
('amlodipineasamlodipinebesilate','amlodipinebesilate','e njëjta formë, shprehur ndryshe','',''),
('lisinoprilaslisinoprildihydrate','lisinoprildihydrate','e njëjta formë, shprehur ndryshe','',''),
('rosuvastatinasrosuvastatincalcium','rosuvastatincalcium','e njëjta formë, shprehur ndryshe','',''),
('methylprednisoloneassodiumsuccinate','methylprednisolonesodiumsuccinate','e njëjta formë, shprehur ndryshe','',''),
('methylprednisolonesodiumsuccinateeqtomethylprednisolone','methylprednisolonesodiumsuccinate','e njëjta formë, shprehur ndryshe','',''),
('triptorelineasacetate','triptorelineacetate','e njëjta formë, shprehur ndryshe','',''),
('palonosetronhydrochlorideaspalonosetron','palonosetronhydrochloride','e njëjta formë, shprehur ndryshe','',''),
('cefradinemonohydratecefradina','cefradinemonohydrate','e njëjta formë, shprehur ndryshe','',''),
('policresulencinchocainhydrochlorid','policresulencinchocainehydrochloride','e njëjta formë, shprehur ndryshe','',''),
('ciprofloxacinhydrochloride1h2o','ciprofloxacinhydrochloride','monohidrat, shprehur ndryshe','',''),
('metronidazolemiconazolenitratelidocainebase','metronidazolemiconazolenitratelidocaine','lidocaine base = lidocaine','',''),
('lidocainehydrochlorideepinephrinebase','lidocainehydrochlorideepinephrine','epinephrine base = epinephrine','',''),
('amlodipineinformofamlodipinebesilate1387mgatorvastatininformofatorvastatincalciumtrihydrate108500','amlodipineinformofamlodipinebesilate1387mgatorvastatininformofatorvastatincalciumtrihydrate1085mg','e njëjta forcë, shkruar pa njësi','',''),
-- Tekst i dyfishuar në burim
('hydrochlorothiazidehydrochlorothiazide','hydrochlorothiazide','tekst i dyfishuar','',''),
('benzydaminehclbenzydaminehcl','benzydaminehcl','tekst i dyfishuar','',''),
('paracetamolcaffeineparacetamolcaffeine','paracetamolcaffeine','tekst i dyfishuar','',''),
('aminophylineaminophylline','aminophylline','tekst i dyfishuar','',''),
('fluoxetinehydrochloridefluoxetine','fluoxetinehydrochloride','tekst i dyfishuar','',''),
('ciprofloxacinhydrochloridemonohydrateciprofloxacin','ciprofloxacinhydrochloridemonohydrate','tekst i dyfishuar','',''),
('ibuprofenibuprofenum','ibuprofenum','tekst i dyfishuar','',''),
-- I njëjti kombinim, përbërësit të renditur ndryshe
('paracetamolchlorpheniraminemaleatepseudoephedrinehcl','paracetamolpseudoephedrinehclchlorpheniraminemaleate','rend i ndryshëm përbërësish','',''),
('formoterolfumaratedihydratefluticasonepropionate','fluticasonepropionateformoterolfumaratedihydrate','rend i ndryshëm përbërësish','',''),
('gentamicinsulphatedexamethasonesodiumphosphate','dexamethasonesodiumphosphategentamicinsulphate','rend i ndryshëm përbërësish','',''),
('gentamicinsulfatebetamethasonedipropionate','betamethasonedipropionategentamicinsulfate','rend i ndryshëm përbërësish','',''),
('penicillingpotassiumpenicillingprocaine','penicillingprocainepenicillingpotassium','rend i ndryshëm përbërësish','',''),
('pheniraminemaleateparacetamolascorbicacid','paracetamolascorbicacidpheniraminemaleate','rend i ndryshëm përbërësish','',''),
('thiaminehydrochloridepyridoxinehydrochlorideriboflavinsodiumphosphatenicotinamidedexpanthenol','thiaminehydrochlorideriboflavinsodiumphosphatepyridoxinehydrochloridenicotinamidedexpanthenol','rend i ndryshëm përbërësish','',''),
('sodiumchloridepotassiumchloridecalciumchloridedihydratesodiumlactate','sodiumlactatesodiumchloridepotassiumchloridecalciumchloridedihydrate','rend i ndryshëm përbërësish','',''),
('calciumchloridedihydratepotassiumchloridesodiumchloridesodiumlactate','sodiumlactatesodiumchloridepotassiumchloridecalciumchloridedihydrate','rend i ndryshëm përbërësish','','')
on conflict (variant_key) do nothing;

update public.substance_aliases set decided_by = 'claude-review-2026-08-27' where decided_by = '';
