-- Synced from Supabase production migration history.
-- version: 20260819123429
-- name: restore_medindex_constraints

alter table public.clinical_sources add constraint clinical_sources_pkey PRIMARY KEY (id);
alter table public.content_versions add constraint content_versions_pkey PRIMARY KEY (id);
alter table public.dosage_regimens add constraint dosage_regimens_pkey PRIMARY KEY (id);
alter table public.dose_indications_v2 add constraint dose_indications_v2_pkey PRIMARY KEY (indication_key);
alter table public.dose_products_v2 add constraint dose_products_v2_pkey PRIMARY KEY (product_key);
alter table public.dose_rule_products_v2 add constraint dose_rule_products_v2_pkey PRIMARY KEY (rule_product_key);
alter table public.dose_rules_v2 add constraint dose_rules_v2_pkey PRIMARY KEY (rule_key);
alter table public.dose_safety_v2 add constraint dose_safety_v2_pkey PRIMARY KEY (safety_key);
alter table public.dose_sources_v2 add constraint dose_sources_v2_pkey PRIMARY KEY (source_key);
alter table public.drug_clinical_profiles add constraint drug_clinical_profiles_pkey PRIMARY KEY (drug_id);
alter table public.drug_indications add constraint drug_indications_pkey PRIMARY KEY (id);
alter table public.drugs add constraint drugs_pkey PRIMARY KEY (id);
alter table public.icd_codes add constraint icd_codes_pkey PRIMARY KEY (id);
alter table public.icd_hierarchy_nodes add constraint icd_hierarchy_nodes_pkey PRIMARY KEY (revision, code);
alter table public.icd_hierarchy_revisions add constraint icd_hierarchy_revisions_pkey PRIMARY KEY (revision);
alter table public.lab_categories add constraint lab_categories_pkey PRIMARY KEY (id);
alter table public.lab_tests add constraint lab_tests_pkey PRIMARY KEY (id);
alter table public.medindex_drug_core_map_v1 add constraint medindex_drug_core_map_v1_pkey PRIMARY KEY (source_drug_id);
alter table public.medindex_product_metadata_verifications_v1 add constraint medindex_product_metadata_verifications_v1_pkey PRIMARY KEY (product_identity_id, field_name, verified_value);
alter table public.medindex_product_overrides_v1 add constraint medindex_product_overrides_v1_pkey PRIMARY KEY (source_drug_id);
alter table public.medindex_registry_audit_v2 add constraint medindex_registry_audit_v2_pkey PRIMARY KEY (product_identity_id);
alter table public.medindex_source_gap_resolutions_v1 add constraint medindex_source_gap_resolutions_v1_pkey PRIMARY KEY (product_identity_id);
alter table public.medindex_value_map_v1 add constraint medindex_value_map_v1_pkey PRIMARY KEY (domain, raw_value);
alter table public.dosage_regimens add constraint dosage_regimens_source_key_key UNIQUE (source_key);
alter table public.dose_rule_products_v2 add constraint dose_rule_products_v2_unique UNIQUE (rule_key, product_key);
alter table public.drug_indications add constraint drug_indications_drug_id_indication_name_population_key UNIQUE (drug_id, indication_name, population);
alter table public.drugs add constraint drugs_registry_number_key UNIQUE (registry_number);
alter table public.icd_codes add constraint icd_codes_code_key UNIQUE (code);
alter table public.lab_categories add constraint lab_categories_category_number_key UNIQUE (category_number);
alter table public.lab_tests add constraint lab_tests_category_form_name_key UNIQUE (category_id, form_name);
alter table public.content_versions add constraint content_versions_source_type_check CHECK (source_type = ANY (ARRAY['google_sheets'::text, 'github'::text, 'editor'::text, 'import'::text]));
alter table public.content_versions add constraint content_versions_status_check CHECK (status = ANY (ARRAY['draft'::text, 'reviewed'::text, 'published'::text, 'archived'::text]));
alter table public.dosage_regimens add constraint dosage_regimens_calculation_status_check CHECK (calculation_status = ANY (ARRAY['text_verified'::text, 'calculable_verified'::text, 'pending'::text, 'not_recommended'::text, 'contraindicated'::text]));
alter table public.dosage_regimens add constraint dosage_regimens_calculation_type_check CHECK (calculation_type IS NULL OR (calculation_type = ANY (ARRAY['mg_per_kg_dose'::text, 'mg_per_kg_day'::text, 'mcg_per_kg_dose'::text, 'ml_per_kg_dose'::text, 'fixed_dose'::text, 'fixed_volume'::text])));
alter table public.dosage_regimens add constraint dosage_regimens_editorial_status_check CHECK (editorial_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'verified'::text, 'published'::text, 'archived'::text]));
alter table public.dosage_regimens add constraint dosage_regimens_population_check CHECK (population = ANY (ARRAY['adult'::text, 'pediatric'::text]));
alter table public.dosage_regimens add constraint dosage_regimens_published_requires_drug_check CHECK (editorial_status <> 'published'::text OR drug_id IS NOT NULL);
alter table public.dose_indications_v2 add constraint dose_indications_v2_age_check CHECK (min_age_months IS NULL OR max_age_months IS NULL OR max_age_months >= min_age_months);
alter table public.dose_indications_v2 add constraint dose_indications_v2_group_check CHECK (patient_group = ANY (ARRAY['pediatric_only'::text, 'adult_only'::text, 'pediatric_and_adult'::text]));
alter table public.dose_indications_v2 add constraint dose_indications_v2_nonnegative_check CHECK (COALESCE(min_age_months, 0) >= 0 AND COALESCE(max_age_months, 0) >= 0 AND COALESCE(min_weight_kg, 0::numeric) >= 0::numeric AND COALESCE(max_weight_kg, 0::numeric) >= 0::numeric);
alter table public.dose_indications_v2 add constraint dose_indications_v2_status_check CHECK (editorial_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'verified'::text, 'published'::text, 'archived'::text]));
alter table public.dose_indications_v2 add constraint dose_indications_v2_verified_source_check CHECK ((editorial_status <> ALL (ARRAY['verified'::text, 'published'::text])) OR source_key IS NOT NULL);
alter table public.dose_indications_v2 add constraint dose_indications_v2_weight_check CHECK (min_weight_kg IS NULL OR max_weight_kg IS NULL OR max_weight_kg >= min_weight_kg);
alter table public.dose_products_v2 add constraint dose_products_v2_denominator_unit_check CHECK (denominator_unit = ANY (ARRAY['mL'::text, 'tablet'::text, 'capsule'::text, 'suppository'::text, 'sachet'::text, 'ampoule'::text, 'vial'::text, 'dose'::text]));
alter table public.dose_products_v2 add constraint dose_products_v2_group_check CHECK (patient_group = ANY (ARRAY['pediatric_only'::text, 'adult_only'::text, 'pediatric_and_adult'::text]));
alter table public.dose_products_v2 add constraint dose_products_v2_numerator_unit_check CHECK (numerator_unit = ANY (ARRAY['mg'::text, 'mcg'::text, 'g'::text, 'IU'::text, 'unit'::text, 'mmol'::text, 'mEq'::text, 'mL'::text]));
alter table public.dose_products_v2 add constraint dose_products_v2_rounding_check CHECK (rounding_mode = ANY (ARRAY['exact'::text, 'nearest'::text, 'down'::text, 'up'::text, 'manual'::text]));
alter table public.dose_products_v2 add constraint dose_products_v2_split_check CHECK (tablet_split_denominator = ANY (ARRAY[1, 2, 4]));
alter table public.dose_products_v2 add constraint dose_products_v2_status_check CHECK (editorial_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'verified'::text, 'published'::text, 'archived'::text]));
alter table public.dose_products_v2 add constraint dose_products_v2_values_check CHECK (numerator_value > 0::numeric AND denominator_value > 0::numeric AND (measurable_increment_ml IS NULL OR measurable_increment_ml > 0::numeric));
alter table public.dose_products_v2 add constraint dose_products_v2_verified_source_check CHECK ((editorial_status <> ALL (ARRAY['verified'::text, 'published'::text])) OR source_key IS NOT NULL);
alter table public.dose_rule_products_v2 add constraint dose_rule_products_v2_conversion_check CHECK (conversion_status = ANY (ARRAY['automatic'::text, 'manual_review'::text, 'not_allowed'::text]));
alter table public.dose_rule_products_v2 add constraint dose_rule_products_v2_rounding_check CHECK (rounding_increment_value IS NULL OR rounding_increment_value > 0::numeric);
alter table public.dose_rule_products_v2 add constraint dose_rule_products_v2_status_check CHECK (editorial_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'verified'::text, 'published'::text, 'archived'::text]));
alter table public.dose_rules_v2 add constraint dose_rules_v2_age_check CHECK (min_age_months IS NULL OR max_age_months IS NULL OR max_age_months >= min_age_months);
alter table public.dose_rules_v2 add constraint dose_rules_v2_basis_check CHECK (dose_basis IS NULL OR (dose_basis = ANY (ARRAY['per_dose'::text, 'per_day'::text, 'single_dose'::text])));
alter table public.dose_rules_v2 add constraint dose_rules_v2_dose_range_check CHECK (dose_min_value IS NULL OR dose_max_value IS NULL OR dose_max_value >= dose_min_value);
alter table public.dose_rules_v2 add constraint dose_rules_v2_duration_check CHECK (duration_mode = ANY (ARRAY['single_dose'::text, 'fixed_days'::text, 'range_days'::text, 'prn'::text, 'review_after'::text, 'specialist_plan'::text]));
alter table public.dose_rules_v2 add constraint dose_rules_v2_duration_range_check CHECK (duration_min_days IS NULL OR duration_max_days IS NULL OR duration_max_days >= duration_min_days);
alter table public.dose_rules_v2 add constraint dose_rules_v2_frequency_check CHECK (frequency_mode = ANY (ARRAY['interval'::text, 'times_per_day'::text, 'once'::text, 'prn'::text, 'continuous'::text]));
alter table public.dose_rules_v2 add constraint dose_rules_v2_group_check CHECK (patient_group = ANY (ARRAY['pediatric_only'::text, 'adult_only'::text, 'pediatric_and_adult'::text]));
alter table public.dose_rules_v2 add constraint dose_rules_v2_interval_check CHECK (interval_min_hours IS NULL OR interval_max_hours IS NULL OR interval_max_hours >= interval_min_hours);
alter table public.dose_rules_v2 add constraint dose_rules_v2_method_check CHECK (calculation_method = ANY (ARRAY['fixed_dose'::text, 'fixed_volume'::text, 'dose_per_kg_per_dose'::text, 'dose_per_kg_per_day'::text, 'dose_per_m2_per_dose'::text, 'dose_per_m2_per_day'::text, 'age_band_fixed'::text, 'manual_only'::text]));
alter table public.dose_rules_v2 add constraint dose_rules_v2_method_values_check CHECK (calculation_method = 'manual_only'::text OR dose_min_value IS NOT NULL AND dose_max_value IS NOT NULL AND dose_unit IS NOT NULL AND dose_basis IS NOT NULL);
alter table public.dose_rules_v2 add constraint dose_rules_v2_nonnegative_check CHECK (COALESCE(dose_min_value, 0::numeric) >= 0::numeric AND COALESCE(dose_max_value, 0::numeric) >= 0::numeric AND COALESCE(interval_min_hours, 0::numeric) >= 0::numeric AND COALESCE(interval_max_hours, 0::numeric) >= 0::numeric AND COALESCE(times_per_day, 0::numeric) >= 0::numeric AND COALESCE(max_single_dose_mg, 0::numeric) >= 0::numeric AND COALESCE(max_daily_dose_mg, 0::numeric) >= 0::numeric AND COALESCE(max_doses_24h, 0) >= 0 AND COALESCE(duration_min_days, 0::numeric) >= 0::numeric AND COALESCE(duration_max_days, 0::numeric) >= 0::numeric AND COALESCE(review_after_days, 0::numeric) >= 0::numeric AND COALESCE(min_age_months, 0) >= 0 AND COALESCE(max_age_months, 0) >= 0 AND COALESCE(min_weight_kg, 0::numeric) >= 0::numeric AND COALESCE(max_weight_kg, 0::numeric) >= 0::numeric);
alter table public.dose_rules_v2 add constraint dose_rules_v2_out_of_range_check CHECK (out_of_range_action = ANY (ARRAY['block'::text, 'manual_review'::text, 'not_applicable'::text]));
alter table public.dose_rules_v2 add constraint dose_rules_v2_status_check CHECK (editorial_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'verified'::text, 'published'::text, 'archived'::text]));
alter table public.dose_rules_v2 add constraint dose_rules_v2_unit_check CHECK (dose_unit IS NULL OR (dose_unit = ANY (ARRAY['mg'::text, 'mcg'::text, 'g'::text, 'IU'::text, 'unit'::text, 'mmol'::text, 'mEq'::text, 'mL'::text])));
alter table public.dose_rules_v2 add constraint dose_rules_v2_verified_check CHECK ((editorial_status <> ALL (ARRAY['verified'::text, 'published'::text])) OR source_key IS NOT NULL AND verified_by IS NOT NULL AND verified_at IS NOT NULL);
alter table public.dose_rules_v2 add constraint dose_rules_v2_weight_basis_check CHECK (weight_basis = ANY (ARRAY['none'::text, 'kg'::text, 'm2'::text]));
alter table public.dose_rules_v2 add constraint dose_rules_v2_weight_check CHECK (min_weight_kg IS NULL OR max_weight_kg IS NULL OR max_weight_kg >= min_weight_kg);
alter table public.dose_rules_v2 add constraint dose_rules_v2_weight_method_check CHECK ((calculation_method = ANY (ARRAY['dose_per_kg_per_dose'::text, 'dose_per_kg_per_day'::text])) AND weight_basis = 'kg'::text OR (calculation_method = ANY (ARRAY['dose_per_m2_per_dose'::text, 'dose_per_m2_per_day'::text])) AND weight_basis = 'm2'::text OR (calculation_method = ANY (ARRAY['fixed_dose'::text, 'fixed_volume'::text, 'age_band_fixed'::text, 'manual_only'::text])) AND weight_basis = 'none'::text);
alter table public.dose_safety_v2 add constraint dose_safety_v2_check CHECK (min_age_months IS NULL OR max_age_months IS NULL OR min_age_months <= max_age_months);
alter table public.dose_safety_v2 add constraint dose_safety_v2_editorial_status_check CHECK (editorial_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'verified'::text, 'published'::text, 'archived'::text]));
alter table public.dose_safety_v2 add constraint dose_safety_v2_max_age_months_check CHECK (max_age_months IS NULL OR max_age_months >= 0);
alter table public.dose_safety_v2 add constraint dose_safety_v2_min_age_months_check CHECK (min_age_months IS NULL OR min_age_months >= 0);
alter table public.dose_safety_v2 add constraint dose_safety_v2_patient_group_check CHECK (patient_group = ANY (ARRAY['pediatric_only'::text, 'adult_only'::text, 'pediatric_and_adult'::text]));
alter table public.dose_safety_v2 add constraint dose_safety_v2_severity_check CHECK (severity = ANY (ARRAY['block'::text, 'manual_review'::text, 'caution'::text, 'info'::text]));
alter table public.dose_sources_v2 add constraint dose_sources_v2_status_check CHECK (editorial_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'verified'::text, 'published'::text, 'archived'::text]));
alter table public.dose_sources_v2 add constraint dose_sources_v2_type_check CHECK (source_type = ANY (ARRAY['smPC'::text, 'fda_label'::text, 'ema'::text, 'national_guideline'::text, 'who'::text, 'nice'::text, 'other_official'::text]));
alter table public.dose_sources_v2 add constraint dose_sources_v2_verified_official_check CHECK ((editorial_status <> ALL (ARRAY['verified'::text, 'published'::text])) OR official_source = true);
alter table public.drug_clinical_profiles add constraint drug_clinical_profiles_verification_status_check CHECK (verification_status = ANY (ARRAY['pending'::text, 'in_review'::text, 'verified'::text]));
alter table public.drug_indications add constraint drug_indications_editorial_status_check CHECK (editorial_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'verified'::text, 'published'::text, 'archived'::text]));
alter table public.drug_indications add constraint drug_indications_population_check CHECK (population = ANY (ARRAY['all'::text, 'adult'::text, 'pediatric'::text]));
alter table public.drugs add constraint drugs_approved_population_check CHECK (approved_population IS NULL OR (approved_population = ANY (ARRAY['Pediatric only'::text, 'Adult only'::text, 'Pediatric and adult both'::text, 'E PAPËRCAKTUAR'::text])));
alter table public.drugs add constraint drugs_editorial_status_check CHECK (editorial_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'verified'::text, 'published'::text, 'archived'::text]));
alter table public.drugs add constraint drugs_pediatric_age_unit_check CHECK ((pediatric_min_age_unit IS NULL OR (pediatric_min_age_unit = ANY (ARRAY['ditë'::text, 'javë'::text, 'muaj'::text, 'vjet'::text]))) AND (pediatric_max_age_unit IS NULL OR (pediatric_max_age_unit = ANY (ARRAY['ditë'::text, 'javë'::text, 'muaj'::text, 'vjet'::text]))));
alter table public.drugs add constraint drugs_pediatric_basis_check CHECK (pediatric_dose_basis IS NULL OR (pediatric_dose_basis = ANY (ARRAY['kg/dozë'::text, 'kg/ditë'::text, 'kg/orë'::text, 'kg/min'::text, 'm²/dozë'::text, 'm²/ditë'::text, 'bandë peshe'::text, 'dozë fikse'::text])));
alter table public.drugs add constraint drugs_pediatric_dose_unit_check CHECK (pediatric_dose_unit IS NULL OR (pediatric_dose_unit = ANY (ARRAY['mg'::text, 'mcg'::text, 'g'::text, 'mL'::text, 'unit'::text, 'IU'::text, 'mmol'::text, 'mEq'::text])));
alter table public.drugs add constraint drugs_pediatric_max_doses_per_day_positive CHECK (pediatric_max_doses_per_day IS NULL OR pediatric_max_doses_per_day > 0::numeric);
alter table public.drugs add constraint drugs_pediatric_min_interval_hours_positive CHECK (pediatric_min_interval_hours IS NULL OR pediatric_min_interval_hours > 0::numeric);
alter table public.drugs add constraint drugs_pediatric_nonnegative_check CHECK (COALESCE(pediatric_min_age_value, 0::numeric) >= 0::numeric AND COALESCE(pediatric_max_age_value, 0::numeric) >= 0::numeric AND COALESCE(pediatric_min_weight_kg, 0::numeric) >= 0::numeric AND COALESCE(pediatric_max_weight_kg, 0::numeric) >= 0::numeric AND COALESCE(pediatric_dose_min, 0::numeric) >= 0::numeric AND COALESCE(pediatric_dose_max, 0::numeric) >= 0::numeric AND COALESCE(pediatric_doses_per_day, 0::numeric) >= 0::numeric AND COALESCE(pediatric_interval_hours, 0::numeric) >= 0::numeric AND COALESCE(pediatric_max_single_value, 0::numeric) >= 0::numeric AND COALESCE(pediatric_max_daily_value, 0::numeric) >= 0::numeric AND COALESCE(pediatric_concentration_value, 0::numeric) >= 0::numeric AND COALESCE(pediatric_concentration_per_value, 0::numeric) >= 0::numeric);
alter table public.drugs add constraint drugs_pediatric_range_check CHECK ((pediatric_min_weight_kg IS NULL OR pediatric_max_weight_kg IS NULL OR pediatric_max_weight_kg >= pediatric_min_weight_kg) AND (pediatric_dose_min IS NULL OR pediatric_dose_max IS NULL OR pediatric_dose_max >= pediatric_dose_min) AND (pediatric_doses_per_day IS NULL OR pediatric_doses_per_day > 0::numeric) AND (pediatric_interval_hours IS NULL OR pediatric_interval_hours > 0::numeric) AND (pediatric_concentration_value IS NULL OR pediatric_concentration_value > 0::numeric) AND (pediatric_concentration_per_value IS NULL OR pediatric_concentration_per_value > 0::numeric));
alter table public.drugs add constraint drugs_pediatric_use_status_check CHECK (pediatric_use_status IS NULL OR (pediatric_use_status = ANY (ARRAY['LEJOHET'::text, 'KUFIZUAR'::text, 'NUK REKOMANDOHET'::text, 'KUNDËRINDIKUAR'::text, 'PA TË DHËNA'::text, 'NUK APLIKOHET'::text])));
alter table public.drugs add constraint drugs_pediatric_verification_check CHECK (pediatric_verification_status IS NULL OR (pediatric_verification_status = ANY (ARRAY['needs_source'::text, 'in_review'::text, 'verified'::text, 'not_applicable'::text])));
alter table public.drugs add constraint drugs_pediatric_verified_source_check CHECK (pediatric_verification_status <> 'verified'::text OR pediatric_source_url IS NOT NULL AND pediatric_verified_at IS NOT NULL);
alter table public.drugs add constraint drugs_pediatric_verified_structure_check CHECK (pediatric_verification_status <> 'verified'::text OR pediatric_use_status IS NOT NULL AND pediatric_source_url IS NOT NULL AND pediatric_verified_at IS NOT NULL AND (pediatric_dose_min IS NULL AND pediatric_dose_max IS NULL OR pediatric_dose_unit IS NOT NULL AND pediatric_dose_basis IS NOT NULL));
alter table public.icd_codes add constraint icd_codes_editorial_status_check CHECK (editorial_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'verified'::text, 'published'::text, 'archived'::text]));
alter table public.icd_hierarchy_nodes add constraint icd_hierarchy_nodes_level_name_check CHECK (level_name = ANY (ARRAY['chapter'::text, 'block'::text, 'category'::text, 'subcategory'::text]));
alter table public.icd_hierarchy_revisions add constraint icd_hierarchy_revisions_status_check CHECK (status = ANY (ARRAY['staging'::text, 'active'::text, 'superseded'::text, 'failed'::text]));
alter table public.lab_tests add constraint lab_tests_editorial_status_check CHECK (editorial_status = ANY (ARRAY['draft'::text, 'in_review'::text, 'verified'::text, 'published'::text, 'archived'::text]));
alter table public.dosage_regimens add constraint dosage_regimens_drug_id_fkey FOREIGN KEY (drug_id) REFERENCES drugs(id) ON DELETE CASCADE;
alter table public.dosage_regimens add constraint dosage_regimens_indication_id_fkey FOREIGN KEY (indication_id) REFERENCES drug_indications(id) ON DELETE SET NULL;
alter table public.dose_indications_v2 add constraint dose_indications_v2_source_key_fkey FOREIGN KEY (source_key) REFERENCES dose_sources_v2(source_key) ON DELETE SET NULL;
alter table public.dose_products_v2 add constraint dose_products_v2_drug_id_fkey FOREIGN KEY (drug_id) REFERENCES drugs(id) ON DELETE SET NULL;
alter table public.dose_products_v2 add constraint dose_products_v2_source_key_fkey FOREIGN KEY (source_key) REFERENCES dose_sources_v2(source_key) ON DELETE SET NULL;
alter table public.dose_rule_products_v2 add constraint dose_rule_products_v2_product_key_fkey FOREIGN KEY (product_key) REFERENCES dose_products_v2(product_key) ON DELETE CASCADE;
alter table public.dose_rule_products_v2 add constraint dose_rule_products_v2_rule_key_fkey FOREIGN KEY (rule_key) REFERENCES dose_rules_v2(rule_key) ON DELETE CASCADE;
alter table public.dose_rules_v2 add constraint dose_rules_v2_indication_key_fkey FOREIGN KEY (indication_key) REFERENCES dose_indications_v2(indication_key) ON DELETE CASCADE;
alter table public.dose_rules_v2 add constraint dose_rules_v2_source_key_fkey FOREIGN KEY (source_key) REFERENCES dose_sources_v2(source_key) ON DELETE SET NULL;
alter table public.dose_safety_v2 add constraint dose_safety_v2_indication_key_fkey FOREIGN KEY (indication_key) REFERENCES dose_indications_v2(indication_key) ON DELETE CASCADE;
alter table public.dose_safety_v2 add constraint dose_safety_v2_product_key_fkey FOREIGN KEY (product_key) REFERENCES dose_products_v2(product_key) ON DELETE CASCADE;
alter table public.dose_safety_v2 add constraint dose_safety_v2_source_key_fkey FOREIGN KEY (source_key) REFERENCES dose_sources_v2(source_key) ON DELETE RESTRICT;
alter table public.drug_clinical_profiles add constraint drug_clinical_profiles_drug_id_fkey FOREIGN KEY (drug_id) REFERENCES drugs(id) ON DELETE CASCADE;
alter table public.drug_indications add constraint drug_indications_drug_id_fkey FOREIGN KEY (drug_id) REFERENCES drugs(id) ON DELETE CASCADE;
alter table public.drugs add constraint drugs_source_version_id_fkey FOREIGN KEY (source_version_id) REFERENCES content_versions(id) ON DELETE SET NULL;
alter table public.icd_hierarchy_nodes add constraint icd_hierarchy_nodes_revision_fkey FOREIGN KEY (revision) REFERENCES icd_hierarchy_revisions(revision) ON DELETE CASCADE;
alter table public.lab_tests add constraint lab_tests_category_id_fkey FOREIGN KEY (category_id) REFERENCES lab_categories(id) ON DELETE SET NULL;
alter table public.lab_tests add constraint lab_tests_source_version_id_fkey FOREIGN KEY (source_version_id) REFERENCES content_versions(id) ON DELETE SET NULL;
alter table public.medindex_drug_core_map_v1 add constraint medindex_drug_core_map_v1_source_drug_id_fkey FOREIGN KEY (source_drug_id) REFERENCES drugs(id);
alter table public.medindex_product_overrides_v1 add constraint medindex_product_overrides_v1_source_drug_id_fkey FOREIGN KEY (source_drug_id) REFERENCES drugs(id);
